### ISSUE TITLE
import docx : les mots clés et définitions ne sont pas importés

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#103]
De même, les liens internes "continuer dans l'Atlas" posent problème et génèrent le message d'erreur suivant : 
“Erreur:child "metas" fails because ["metas" at position 7 fails because [child "list" fails because ["list" is not allowed]]]”

**Comment by delphinelrcl** [comment]
Quand on importe un article au format GoogleDoc cela fonctionne (ex avec l'article "énergies fossiles"). Mais pas avec avec les fichiers Word alors que ce sont ces fichiers que nous devons importés car "édités" par l'éditeur.

**Comment by Delapouite** [comment]
Il n'y a pas de discrimination faites lors du parsing entre les `.docx` de Microsoft Word et les Google Docs.

Un test qui peut etre effectué pour m'aider à debloquer cette issue:
1 - Uploader un .docx sur GDrive
2 - Tenter de l'importer sur le bo eAtlas
3 - Si echec, le convertir en Google Doc sans alterer son contenu
4 - Tenter à nouveau de l'importer sur le bo eAtlas

**Comment by Delapouite** [comment]
J'ai enfin pu trouver le soucis grace aux docs transmis par @TomBor 

La méta originelle (anciens docs): "Continuer dans l'Atlas"
s'appelle désormais (nouveaux docs): "Continuer dans l’Atlas"

Vous ne voyez pas la différence? Moi non plus… Jusqu'à ce que je fronce les sourcils et passe la police en caractère 100: l'apostrophe est differente ! Le parser était donc incapable de parser cette section inconnue

Résolu dans https://github.com/AtelierCartographie/eatlas/commit/ab8893739ce6302b658590975fd8fdb9275b635e

Une typo soignée est importante dans les contenus, mais les métas doivent être le plus agnostique possibles.
