### ISSUE TITLE
Prise en compte du 0 dans la numérotation des rubriques

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#105]
Les rubriques sont numérotées de 0 à 5 (voir la page d'accueil du front office) ; or sur le back-office, la numérotation commence à 1 et termine à 6.

**Comment by Delapouite** [comment]
Done: https://github.com/AtelierCartographie/eatlas/commit/c28ea6367a4c88bade867b8752f7ceac53c1b95b
