### ISSUE TITLE
Le contenu (vidéo/image) du champ resourceId ne s'affiche pas sur le FO

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#107]
Quand on ajoute via un identifiant une image dans la notice d'une rubrique celle ci ne s'affiche pas sur le FO ; idem si on ajoute un lien vers une vidéo.

**Comment by delphinelrcl** [comment]
De même, il est impossible de modifier l'identifiant d'une rubrique

**Comment by Delapouite** [comment]
Le soucis rencontré était l'absence de message d'erreurs lors de la soumission du resourceId.
Le process est maintenant plus rigoureux et verbeux pour éviter ce problème.

### Création d'un topic

- On ne peut pas fournir de resourceId puisqu'une ressource appartenant à ce topic ne devrait pas pouvoir etre importée. Cas typique de l'œuf et la poule.

### Mise à jour d'un topic

- On ne peut pas changer son id. Le champ est readonly volontairement, le style a été changé pour mieux s'en rendre compte.
- On peut renseigner un resourceId correspondant à la ressource qu'on veut voir s'afficher en entete. Plusieurs contraintes s'appliquent:
  - Le resourceId doit faire reference à une ressource existante.
  - Celle ci doit etre de type vidéo ou image.
  - Enfin son topic doit etre identique au topic que l'on souhaite mettre à jour. Des messages d'erreurs accompagnent l'utilisateur dès qu'un de ces points n'est pas respecté.

**Comment by delphinelrcl** [comment]
Impossible de télécharger une ressource id (vidéo ou photo) ; le message d'erreur suivant apparaît : Erreur:Unknown Resource Id
