### ISSUE TITLE
Erreur d'affichage du champ auteur dans le tableau de bord

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#108]
Quand on dépose une ressource dans le BO, on a systématiquement dans le tableau de bord un point d'exclamation dans la colonne "auteur", que le champ soit vide ou non. Pourquoi ?

![image](https://user-images.githubusercontent.com/35258993/38996429-77ea1d62-43eb-11e8-871f-7f66ca873eac.png)

**Comment by Delapouite** [comment]
Je laisserai Nicolas répondre sur ce point lorsqu'il reinterviendra sur le projet.
Il fait mention à cette colonne dans https://github.com/AtelierCartographie/eatlas/issues/65#issuecomment-367287637

D'apres le code actuel, le warning s'affiche quand l'utilisateur est inconnu. Or, pour savoir si on le connait on se base sur un email.
Cela a du sens pour le colonne Déposant (et on constate que ça marche), mais ça ne peut pas marcher pour la colonne Auteur, étant donné que cette info est un nom (extrait du word pour les articles) et non pas un email.

Je ne sais pas trop quelle était l'intention d'origine. Je botte en touche pour le moment et revisiterais plus tard.

**Comment by naholyr** [comment]
C'est une simple incompréhension de l'origine de la valeur du champ "author" je pense ;) le commit l'ayant mis en place est ici : 719b970a5a71a69fc8b4152f0a11018e40e5bf03 j'ai du traiter les deux cas d'un bloc pensant que l'auteur était censé être un utilisateur de la plateforme au même titre que le déposant. Je vais simplement annuler cette contrainte sur la colonne "auteur".
