### ISSUE TITLE
Les images ne s'affichent pas sur le FO lors de la publication d'un article

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#110]
Quand on publie un article, l'image header ne s'affiche ni sur la page de la rubrique ni sur la page de l'article ; idem pour les documents : l'url des ressources est incomplète...   

![image](https://user-images.githubusercontent.com/35258993/38997037-c5055a98-43ec-11e8-9b61-0db70d5466f7.png)

**Comment by naholyr** [comment]
Localement j'ai pu reproduire des images cassées en uploadant des cartes incomplètes, mais dans l'exemple données les URLs semblent correctes.

Quand tu dis que "l'URL des ressources est incomplète" c'est qu'il manque un préfixe (type "/media") ? Ou plutôt que le nom de fichier est invalide (genre un "map-" en trop au début) ?

* Si c'est le premier cas, a priori c'est un problème de configuration : voir `REACT_APP_MEDIA_SUBPATH` (qui vaut "media" par défaut) et `REACT_APP_FRONT_URL` (qui vaut "http://localhost:3000/generated" par défaut) et dans la config serveur `publicUrl` et `mediaSubPath`. Si ce sont les URLs de preprod je pense que cette config est bonne.
* Si c'est le second cas, c'est un problème de nom de fichiers qui a changé, je vais essayer de le corriger mais il faudra ré-uploader les fichiers ou les renommer manuellement parce que le lien entre la ressource et le fichier uploadé va être perdu

**Comment by delphinelrcl** [comment]
Aucune image (carte ou photo publiée) ne s'affiche sur le front alors que cela fonctionne pour la preview.

**Comment by TomBor** [comment]
voir #132 sur les questions de format
