### ISSUE TITLE
Rendre les liens hypertextes actifs pour les ressources de type article et focus

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#118]
Les liens hypertextes sont inactifs dans le corps des articles et les notes ; idem pour les styles (gras et italique).

**Comment by Delapouite** [comment]
travaux en cours à partir du commit https://github.com/AtelierCartographie/eatlas/commit/14c2e443522587aca6f6993ca728999d551381e2

**Comment by Delapouite** [comment]
Cette tache s'est averée plus complexe que prévue:

- les styles (gras `<strong>` et italique `<em>`) n'étaient pas collectés lors de la phase d'import d'un document word. On ne conservait que la matière brute du texte des paragraphes,  les footnotes, les liens externes et les définitions du lexiques. **Par conséquent cela signifie que tous les docs doivent être réimportés** (oui c'est pénible désolé).
- les anciens docs fournis (4A07 par exemple) utilisaient le système de footnotes de Word. Désormais de ce que je vois dans les versions plus récentes, c'est la méta `Références` qui fait foi. Il a donc fallu que j'applique le même strategème d'extraction des styles et liens pour les paragraphes, footnotes et la méta Référence (ces deux dernières sources étant fusionnées).
- le parser de doc word utilisé renvoie une série de tokens mais ne conserve pas les espaces séparateurs. Concrètement ça veut dire que sans intervention à l'affichage, le texte donnerait:

mot normal**mot en gras**mot suivant

au lieu de

mot normal **mot en gras** mot suivant

J'ais donc réappliqué quelques règles propres à la typo française, par exemple pas s'espace avant un point `.`, mais un espace devant un point d'exclamation `!` ou un point d'interrogation `?` etc… Ce système n'est certainement pas encore parfait et il faudra certainement l'ajuster pour certaines exceptions (insécabilité…)
