### ISSUE TITLE
Le téléchargement d'un nouveau docx n'est pas pris en compte quand un fichier est déjà téléchargé

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#119]
Mise à jour d'une ressource de type article ou focus avec re-upload d'un docx non prise en compte. Obligé de le supprimer pour en créer un nouveau.

**Comment by naholyr** [comment]
Quand tu dis "non prise en compte", ça signifie que le site front n'était pas regénéré ? Ou bien que le contenu de l'article n'était pas mis à jour ?

* Si c'est le premier cas (a priori je pense qu'on parle bien de ça), c'est maintenant corrigé par le commit 24ab1a39e6b4b4df445550da5ed8bee7ce4442f3
* Si c'est le second cas, je ne le reproduis pas de mon côté (les metas, nodes, & co sont bien mises à jour au ré-upload)

Je clos en pariant sur le cas n°1 ;)
