### ISSUE TITLE
Intégrer un éditeur dans les champs titre, sous-titre, description et source (copyright) pour toutes les ressources

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#124]
Il faut pouvoir gérer le style de texte (italiques, gras) et les hyperliens dans les champs titre, sous-titres, sources (copyright) et description.

**Comment by Delapouite** [comment]
![image](https://user-images.githubusercontent.com/39315/40619210-7e6fab62-6294-11e8-9314-704e736d124b.png)

**Comment by naholyr** [comment]
Déjà OK pour la description de topic (thanks @Delapouite).

Est-ce qu'on garde l'idée d'avoir un éditeur wysiwyg pour les titres de ressource ? L'intégration de styles personnels dans cette zone est assez risquée pour la mise en forme (sans compter l'accessibilité).

**Comment by TomBor** [comment]
On garde l'idée mais tous les styles ne sont pas utiles dans les titres.
Nous aurions seulement besoin de l'italique et du gras. Pas de liste, ni de retrait ou de liens.
Ça permettra peut être de limiter les risques.

**Comment by TomBor** [comment]
Est-ce qu'il est possible simplement de rendre cet éditeur plus stricte ? Par exemple, si on fait un copier-coller pour remplir le champs, que ce soit sans garder les styles. Ou d'avoir un bouton pour supprimer tous les styles.
L'idée est d'éviter les risques que tu mentionnes.

**Comment by naholyr** [comment]
C'est en effet possible, [l'éditeur est personnalisable (ouf)](https://jpuri.github.io/react-draft-wysiwyg/#/docs?_k=jjqinp), en revanche ce qui sera plus compliqué c'est de conserver la mise en forme actuelle dans l'article (s'il y a du gras dans le titre dans le doc google, il ne sera pas repris). À voir si c'est important pour vous ou si pouvoir retoucher dans le formulaire est suffisant.

**Comment by TomBor** [comment]
Bonne nouvelle ! Une retouche dans le formulaire est suffisant pour nous.
Merci

**Comment by TomBor** [comment]
Depuis les dernières modifications, le titre d'une ressource se retrouve entouré d'une balise <p> (idem pour les styles <b> <em>...)
![capture d ecran 2018-09-10 a 10 02 01](https://user-images.githubusercontent.com/8322713/45284353-9927da80-b4e0-11e8-9059-a3785462df59.png)
