### ISSUE TITLE
Redimensionner l'image de présentation de la rubrique 

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#126]
pour la caler avec le texte

**Comment by Delapouite** [comment]
Pour m'aider dans ce calage, pouvez me fournir l'image qui pose problème?

Par exemple dans mes tests je ne m'etais pas rendu compte du soucis car l'image *bidon* que j'utilisais rentre dans le cadre:

![image](https://user-images.githubusercontent.com/39315/39517400-0b41d564-4e00-11e8-9fa5-bfe4ec7910e1.png)

**Comment by antoinerio** [comment]
Un aperçu : 
![bug-rubrique-image](https://user-images.githubusercontent.com/16940767/39517904-99877e54-4e01-11e8-9549-f644a9f4d69b.png)

Voilà l'image (3 résolutions)
![2p01](https://user-images.githubusercontent.com/16940767/39517836-6121a116-4e01-11e8-876f-2441eb28282d.jpg)
![2p01 2x](https://user-images.githubusercontent.com/16940767/39517837-6137027c-4e01-11e8-9c30-ecab114647bb.jpg)
![2p01 3x](https://user-images.githubusercontent.com/16940767/39517838-614cd1a6-4e01-11e8-852e-e51d5955bd16.jpg)
