### ISSUE TITLE
Lexique : gestion des alias 

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#129]
Comment gérer les pluriels et les genres ?

**Comment by delphinelrcl** [comment]
autre demande : comment gérer les renvois internes au lexique, par exemple quand une définition renvoie vers une autre définition.  Deux options : 
1) on "allume" le mot pour qu'il soit reconnu au parsage comme une définition "normale"
2) on crée une nouvelle métadonnée
Qu'en pensez-vous ?

**Comment by naholyr** [comment]
* Pour les pluriels et les genres, le plus simple a priori est de déclarer les alias dans le lexique, ça évitera de se prendre les pieds dans le tapis avec les irréguliers et autres faux amis
  * Pour ça pas de développement à prévoir à part dans la génération de l'article vérifier (et si ce n'est pas en place, le faire) que les alias sont bien pris en compte dans la recherche de la définition. Le moteur de recherche et le stockage sont déjà OK côté alias normalement.
* Pour les définitions imbriquées, on doit pouvoir reprendre le même principe que les articles en effet, ça implique :
  * modifier le parsing du lexique pour garder les mots "allumés" (comme dans un article)
  * modifier la génération pour pointer vers la définition
  * ça semble plus simple que la création d'une nouvelle méta-données, aussi bien pour le développement que pour la saisie, en revanche niveau front-end comment ça se passerait au clic sur une "sous-définition" ? On remplace le panneau actuel de la définition par la nouvelle ? On les cumule ?

**Comment by TomBor** [comment]
Au niveau front-end, lors d'un clic sur une sous-définition, on propose comme action de renvoyer vers la page de la définition (= résultat d'une recherche avec cette définition OU ancre vers la définition de la page de la liste des définitions).

**Comment by naholyr** [comment]
Afin de mettre en place cette fonctionnalité, la première étape fut de mettre en place une *vraie* page "lexique" non basée sur le moteur de recherche, non paginée. Afin d'économiser au mieux j'ai repris les styles de la page de recherche. A priori ce sera plutôt bon pour le SEO également puisqu'on peut imaginer un meilleur référencement des définitions (à valider).

Impact sur la configuration : la clé ``pageUrls.definition`` disparaît, au profit de ``pageUrls.lexicon``.

Maintenant que c'est en place :

- [ ] Mettre à jour les différents liens
- [ ] Implémenter les ancres

**Comment by naholyr** [comment]
Ping @jri-sp → ajout dans le mapping ES du champ ``definitions.lexicon`` (type "text") dans l'index ``resource``, l'auto-migration gérera ça.

**Comment by naholyr** [comment]
Ping @jri-sp → ajout dans le mapping ES du champ ``definitions.lexicon`` (type "text") dans l'index ``resource``, l'auto-migration gérera ça.

Ping @TomBor @delphinelrcl voici le résultat final :

Ajout du lien vers une autre définition en colorant en rouge dans le lexique (le match sera fait de manière insensible à la casse en cherchant dans le titre ou les alias), exemple ici avec la fausse définition « consolidation de la paix » :
![image](https://user-images.githubusercontent.com/214067/43826394-7cf7a46a-9af7-11e8-885f-bedc04c8abb3.png)

Dans l'article on retrouve la définition, le titre de la modale pointe vers la page du lexique, idem pour les définitions internes :

![image](https://user-images.githubusercontent.com/214067/43826503-c2c59fce-9af7-11e8-9ff2-937104063248.png)

![image](https://user-images.githubusercontent.com/214067/43826650-1b30da2a-9af8-11e8-834e-d37987f11279.png)

Qui pointe maintenant vers une page dédiée, permettant plus facilement de faire un lien direct tout en conservant un listing complet :

![image](https://user-images.githubusercontent.com/214067/43826674-2e553600-9af8-11e8-8828-1b67c76f9e65.png)

Si cette page s'avère trop lourde il ne sera pas compliqué de revenir en arrière et de remettre des liens vers la page de recherche à la place.
