### ISSUE TITLE
Trouver un autre moyen de récupérer la version

### ISSUE THREAD

**Issue by jri-sp** [AtelierCartographie/eatlas#130]
Le mécanisme pour récupérer la version (yarn git-version, etc) ne fonctionne pas dans l'image docker car on n'embarque pas le dossier `.git`.

Dans une image docker on n'embarque le strict minimum pour faire fonctionner l'application, afin de garder de petites images et contrôler ce qu'on y met, donc j'aimerai éviter d'ajouter ce répertoire.

On peut éventuellement copier juste le fichier `.git/ORIG_HEAD` et récupérer les sept premiers caractères ? (`cat .git/ORIG_HEAD | head -c 7`)

**Comment by Delapouite** [comment]
Oui tu as raison il faudrait s'en tirer autrement que passer par `.git`, j'aime bien ta proposition.

Voici un exemple de contenu du fichier `client/src/git-version.js`:

```
export default "34cc330"
```

**Comment by jri-sp** [comment]
J'ai fait ce commit : https://github.com/AtelierCartographie/eatlas/commit/1fea4761cec2a3556e3aa3ba1f88ef051a5811fb

Ça à l'air de fonctionner à la fois dans Docker et en local en lançant avec `yarn dev`. 
Mais je veux bien votre avis de devs avant de mettre ça en prod.

**Comment by Delapouite** [comment]
Je confirme, ça fonctionne et c'est beaucoup plus propre que ce que j'avais proposé.

Merci d'avoir pris les devants sur ce soucis Jeremy !
