### ISSUE TITLE
méta "date de publication" : impossible d'importer une ressource

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#131]
Quand on essaie d'importer une ressource de type article / image / carte / son / vidéo / lexique, on a systématiquement ce message d'erreur, lequel provient de la nouvelle meta "date de publication" :  
"Erreur:ValidationError: child "visiblePublishedAt" fails because ["visiblePublishedAt" must be a valid timestamp or number of milliseconds]"

Pour les focus, le problème vient d'une autre méta :  
"Erreur:ValidationError: child "titlePosition" fails because ["titlePosition" is not allowed]"

On est donc complètement bloqué...

**Comment by naholyr** [comment]
Ça devrait être bon, j'ai passé 2h à tourner autour alors que finalement ce n'était que des erreurs au niveau du schéma de validation lui-même… J'ai pu localement importer des éléments avec succès, je teste la génération du site complet à la prochaine session demain.

Sincèrement désolé pour ce bug bébéte qui vous a bloqué longuement.

**Comment by antoinerio** [comment]
Bonjour,
Merci Nicolas !
Serait-il maintenant possible de pouvoir tester cette nouvelle version sur
notre préprod ?
Jérémy, pourrais-tu peux être nous aider sur ce point ?
Merci !

Antoine Rio
Cartographe

[image: Sciences Po]
Atelier de cartographie
27 Rue Saint-Guillaume 75007 Paris
T. +33 (0)1 45 49 53 26
www.sciencespo.fr/cartographie
www.facebook.com/SciencesPoCarto
[image: Twitter Sciences Po] <https://twitter.com/sciencespo>
<https://www.facebook.com/sciencespo>
<https://www.linkedin.com/edu/school?id=12454>

Le 26 juin 2018 à 00:17, Nicolas Chambrier <notifications@github.com> a
écrit :

**Comment by jri-sp** [comment]
Bonjour,

Les dernières modifications sont maintenant déployées en préprod.

Jérémy


Le 27/06/2018 à 09:38, Antoine Rio a écrit :

**Comment by delphinelrcl** [comment]
Impossible d'importer une ressource. Le message d'erreur qui s'affiche est toujours lié à la date de publication : 
Erreur:ValidationError: child "visiblePublishedAt" fails because ["visiblePublishedAt" must be a valid timestamp or number of milliseconds]

La version de la PPRD est : version: 9fe0ed6 
Est ce la bonne version ?

Pour rappel, vous avez désormais accès à la PPRD avec les identifiants suivants : 
http://eatlas-pprd.sciences-po.fr/admin/login
bruno.heridet@sciencespo.fr
L415g1jqwR

**Comment by antoinerio** [comment]
Bonjour
En effet, nous avons toujours cette erreur bloquante. Pour info la version
déployée sur la préprod est la 9fe0ed6.
Antoine

Antoine Rio
Cartographe

[image: Sciences Po]
Atelier de cartographie
27 Rue Saint-Guillaume 75007 Paris
T. +33 (0)1 45 49 53 26
www.sciencespo.fr/cartographie
www.facebook.com/SciencesPoCarto
[image: Twitter Sciences Po] <https://twitter.com/sciencespo>
<https://www.facebook.com/sciencespo>
<https://www.linkedin.com/edu/school?id=12454>

**Comment by TomBor** [comment]
@jri-sp @naholyr 
Ça pourra peut être aider, j'ai pu faire fonctionner en local l'etlas sans l'erreur de métadonnées en étant sur la dernière version  9fe0ed6.

**Comment by naholyr** [comment]
Bonsoir,

Je n'ai plus les erreurs initialement reportées (sur "titlePosition" et "visiblePublishedAt", par contre j'en ai une nouvelle :

> Erreur:child "metas" fails because ["metas" at position 6 fails because [child "list" fails because ["list" is required]]]

lors de l'import de 4A07 (la version que j'ai en archive). Est-ce de ça dont on parle maintenant ? Je vais voir ce qui cause cette erreur, sans doute une modification du parsing non reportée sur les schémas, je ne pense pas qu'un document invalide puisse en être la cause.

**Comment by naholyr** [comment]
L'erreur que j'ai rencontré sur 4A07 venait d'un problème de contenu, plutôt que d'être trop permissif j'ai préféré préciser l'erreur, on obtient maintenant

> La méta "Mots-clé" attend une liste, mais un simple texte a été fourni

Donc a priori le dernier fix fonctionne, il faudrait vérifier que le serveur node a bien été mis à jour et redémarré (peut-être avez-vous relancé seulement le front ?).

- J'ai pu importer 6A09 sans encombre
- Le bouton preview fonctionne OK
- Ensuite j'ai modifié la "visiblePublishedAt" et elle apparaît bien dans le header de la preview de l'article
- J'ai importé 3A09, publié, la génération s'est bien passée

A priori tout fonctionne donc les problèmes qui pourraient rester seraient de l'ordre de la configuration des dossiers, je peux me rendre disponible jeudi pour faire un point sur la config avec Jérémy s'il y a toujours besoin d'ici là.

**Comment by Delapouite** [comment]
Fonctionne une fois le serveur redemarré.
