### ISSUE TITLE
Type image et carte

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#132]
D'après les preview et en regardant un peu le code. Voici les derniers points sur le rendu des ressources de type image et carte.

**Carte**

- [x]   Il manque l'appel du script picturefill.min.js dans le fichier [Body.js](https://github.com/AtelierCartographie/eatlas/blob/master/client/src/components/preview/Body.js) pour que les différentes tailles de fichier s'affichent.
`h('script', { src: prefixUrl('/assets/js/picturefill.min.js', options.preview) }),`
- [x]   en preview, les différents `srcset=` dirigent tous vers le même fichier (toujours le small). Alors qu'a la publication d'une ressource carte dans le BO reconnait bien les variations de tailles et de densités
- [x]   ce fonctionnement valable dans les pages article et focus doit aussi être appliqué dans la page ressource qui ne réutilise pas le système des `srcset` dans une balise `picture`

**Photo**

- [x]   il y a peut être eu des messages contradictoires sur ce point, mais actuellement seul le format large d'une image est affiché. Or le même système de fonctionnement (avec picturefill) que les cartes doit être appliqué ici. Par contre seulement avec plusieurs tailles (les fichiers n'ont pas plusieurs densités)
- [x]   idem carte, le fonctionnement est aussi valable avec la page ressource

**Carte et photo**

- [ ]   entre les passages d'une taille à une autre, l'image doit être responsive. Actuellement sa largeur est fixe.
- [x]   La résolution des cartes et diagrammes sur écran Rétina est divisée par 2

**Comment by TomBor** [comment]
Et j'oubliais, dans le cas de carte ou image avec format large, la ressource dépasse du `container` et la balise `figure` doit avoir la class `container-fluid`.
C'est valable dans la page article et la page ressource.

**Comment by TomBor** [comment]
Une remarque supplémentaire sur la ressource Carte les différentes tailles (large, medium, small) ne sont pas obligatoire.
Actuellement, si une carte n'a que le format small, la div affiche une icone de lien brisé tant que la largeur d'écran ne correspond pas au format small.

Le comportement attendu, serait d'afficher le plus grand format disponible. Si le format large n'existe pas, il faut afficher le medium et si le medium n'existe pas, on affiche le small. Le format small est le dénominateur commun, il existe obligatoirement pour toutes les ressources cartes.
Exemples : 
- carte `small`, avec un viewport desktop le format small est affiché
- carte `small` et `medium`, avec un viewport desktop le format medium est affiché.

**Comment by TomBor** [comment]
- [ ] ajouter le lien au bouton “Info & téléchargement”  : vers la page ressource de cette ressource

**Comment by antoinerio** [comment]
Je dois avouer que les aspects techniques m'échappent un peu pour cette partie, @TomBor a beaucoup plus expérimenté le sujet.
Si cela peut être utile pour répondre à tes questions, ce prototype résume le comportement attendu des images niveau responsive : http://www.sciencespo.fr/cartographie/khartis/e-Atlas/
Ce prototype se comporte aussi bien sur des écrans Rétina.

**Comment by naholyr** [comment]
Merci en effet il devrait être suffisant de comparer les deux sources et d'appliquer ce qui manque

**Comment by naholyr** [comment]
>  en preview, les différents srcset= dirigent tous vers le même fichier (toujours le small). Alors qu'a la publication d'une ressource carte dans le BO reconnait bien les variations de tailles et de densités

Je n'ai pas reproduit ce problème en testant avec une image locale pour créer une carte :

![image](https://user-images.githubusercontent.com/214067/43200896-43928d42-9017-11e8-9fb9-5de947dd8468.png)

Peut-être que Bruno l'avait déjà corrigé ? Un souci de positionnement apparaît, c'est nouveau ou ça avait déjà été reporté ?

**Comment by antoinerio** [comment]
Le soucis de positionnement me semble nouveau.

**Comment by naholyr** [comment]
Node : c'est corrigé dans le lot des autres modifs

**Comment by naholyr** [comment]
Note concernant ces deux points :

> entre les passages d'une taille à une autre, l'image doit être responsive. Actuellement sa largeur est fixe.
> La résolution des cartes et diagrammes sur écran Rétina est divisée par 2

Il y avait un bug en preview qui faisait qu'on générait le srcset complet même si on n'avait uploadé que quelques images/densités. C'est corrigé et le comportement en preview est maintenant similaire à ce qu'on a dans le site généré, et les images devraient être correctement responsive. Je n'ai pas pu tester et ne suis donc pas 100% sûr mais je pense que ces points sont corrigés par cette modification. À tester !

**Comment by antoinerio** [comment]
> entre les passages d'une taille à une autre, l'image doit être responsive. Actuellement sa largeur est fixe.
Ce point est toujours d'actualité, malgré la modification d'hier, les images ne sont pas responsive entre le passage d'un format à un autre.

>  La résolution des cartes et diagrammes sur écran Rétina est divisée par 2
C'est réglé ! Merci !

**Comment by antoinerio** [comment]
En revanche, concernant les Focus, les images sont ferrées à gauche alors qu'elles devraient être alignées au centre.

**Comment by naholyr** [comment]
OK, c'est le type "image" qui ne va pas, déjà rien qu'à la soumission : l'issue indiquait qu'on devait passer sur un format multi-taille mono-densité, or c'est exactement l'inverse (on peut uploader plusieurs densités mais seul "large" est retenu), ça doit venir de là

**Comment by naholyr** [comment]
Le formulaire d'upload du type "image" est corrigé (pas de changement sur le type "carte") : on peut uploader 3 tailles, mais seule la densité "1x" est supportée (on peut aussi simplement faire sauter cette contrainte, quite à ce qu'il n'y ait aucune différence technique entre carte et image, initialement il avait été prévu que carte = vectoriel et image = le reste mais comme ça a changé en cours de route, la différence n'a peut-être plus lieu d'être finalement…) :

![image](https://user-images.githubusercontent.com/214067/43269921-2fd6f3a0-90f4-11e8-9e45-9c946e41185f.png)

Niveau affichage j'ai bien le même résultat que pour les cartes :

- large si > 700px
- medium si ≤ 700px et > 560px
- small si ≤ 560px
- centrée

Test sur Chrome et Firefox

**Comment by TomBor** [comment]
C'est presque tout bon pour cette issue !
Le dernier point à régler est simple, mes explications n'était pas assez précise. Il faut rajouter une classe spécifique à boostrap à la balise `img` inclut dans `picture`.
```
<picture>
       <source srcset="large..." media="(min-width: 700px)">
       <source srcset="medium..." media="(min-width: 560px)">
       <source srcset="small...">
       <img srcset="..." class="img-responsive center-block"></picture>
```

Comme ça le passage entre les formats est progressive. Et l'image est toujours comprise dans la largeur du navigateur.

**Comment by naholyr** [comment]
Ça devrait être OK maintenant !

**Comment by TomBor** [comment]
C'est parfait, merci !
