### ISSUE TITLE
Front office : supprimer les articles suivant et précédent en bas de l'article

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#136]
Dans un article, les articles suivant et précédent sont uniquement indiqués par des flèches tout au long de l'article ; ils ne sont pas repris en bas de page avec les vignettes (cf capture d'écran ci-dessous) : 

![image](https://user-images.githubusercontent.com/35258993/42332278-dbdab106-8077-11e8-8c2f-f097ae1b5647.png)

**Comment by TomBor** [comment]
Désolé de la contradiction.
Ce bloc de navigation en bas d'article est bien nécessaire surtout pour le format mobile qui n'a pas les flèches flottantes.

Pour résumer, comme l'indique la charte graphique (p.14) : 
Mobile => seulement bloc en bas
Desktop => bloc en bas **+** flèches flottantes

**Comment by delphinelrcl** [comment]
ok
