### ISSUE TITLE
Front office : ajouter les résumés en anglais 

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#137]
Il faut pouvoir ajouter pour les articles et les rubriques un résumé en anglais (voir charte graphique p.5).

**Comment by Delapouite** [comment]
Fait pour les rubriques dans https://github.com/AtelierCartographie/eatlas/commit/59f2ae93b43956f76c0c6b73122972b899fe85f5 (et commit parent)

**Comment by naholyr** [comment]
Focus inclus ?

**Comment by antoinerio** [comment]
Non, uniquement pour les rubriques et articles. Merci !

**Comment by naholyr** [comment]
À tester.

Rappel :

* Lors du démarrage du serveur, il devrait systématiquement créer un nouvel index (message *New index eatlas_topic_...*) pour topic et maintenant resource
* Pour éviter ce problème, **depuis le dossier `server`, lancer le script `npm run migrate-description-issue-137`**
  * Le rôle de ce script est de modifier les documents pour qu'ils collent au schéma déclaré : ajout de `description_fr` (reprenant la valeur de `description` si présent), ajout de `description_en` (texte vide), suppression de `description`
