### ISSUE TITLE
Front Office - focus - ressources ne s'affichent pas

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#138]
Dans les pages Focus, la ressource (image ou carte) ne s'affiche pas.
Alors qu'au niveau du back office, la ressource est bien reconnu.

**Comment by Delapouite** [comment]
Il s'agit d'une grosse incomprehension de ma part.

Je ne sais pas comment je me suis mis ça dans la tête, mais depuis de le début j'étais persuadé que ce qui distinguait un Article d'un Focus (si on exclut le lien de "filiation" permettant de naviguer de l'un vers l'autre) était justement que les Focus ne contenaient pas de Resources mais un contenu purement textuel.

Donc en soi le comportement actuel de non affichage des ressources pour un Focus est celui "attendu" puisque rien n'est fait pour les traiter.

Je vais regarder comment mutualiser au mieux le code opérant pour les articles.

**Comment by naholyr** [comment]
Est-ce la seule fonctionnalité à "repiquer" des articles, ou la frontière focus/article est encore plus fine que ça ?

**Comment by antoinerio** [comment]
Oui, afficher les ressources de type cartes et graphiques, ou photo, est la seule fonctionnalité à repiquer des articles.

**Comment by naholyr** [comment]
Pour information, j'ai réutilisé le même composant que dans le cas de l'article, et donc ça ne concerne pas seulement les images mais également les vidéos et sons, et potentiellement… les focus (récursivité) même si je ne garantis pas l'affichage pour ces derniers.

**Comment by TomBor** [comment]
Merci.
Maintenant la ressource s'affiche bien, mais les exigences de métadonnées liées à un article sont passées au focus (par exemple le résumé qui devrait être falcutatif). Alors que le focus n'a que 5 méta : 
{type}: “focus”
{auteur}: “John Doe”
{partie}: “1”
{identifiant}: “1F01”
{article-associé}: “1A01”

**Comment by naholyr** [comment]
C'est noté, sans doute une erreur dans les schémas de validation, je m'y
attelle vendredi

**Comment by naholyr** [comment]
Je ne suis pas sûr d'avoir compris cette erreur en fait :

> Maintenant la ressource s'affiche bien, mais les exigences de métadonnées liées à un article sont passées au focus (par exemple le résumé qui devrait être falcutatif). Alors que le focus n'a que 5 méta

Quel est l'effet concret ? J'ai corrigé une erreur côté front qui arrivait lorsqu'aucun résumé n'était fourni, est-ce que ça a eu un effet sur ce que tu décris ici ?

**Comment by TomBor** [comment]
L'erreur est bien corrigé à l'usage, en l'absence de méta résumé présente à l'import d'un focus une erreur se déclenchait.

La méta `{Résumé-EN}` fonctionne bien.
Merci !
