### ISSUE TITLE
Ressource copyright - problème style

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#139]
Le texte venant du backoffice (ressource.copyright) est affiché au format html brut : <p><span style="color: rgb(74,74,74);...</p>
![error-copyright](https://user-images.githubusercontent.com/8322713/42517917-29cf8cb4-8461-11e8-99ca-0994121ce636.png)

**Comment by Delapouite** [comment]
Merci.

J'ai réparé cette syncho entre champs markdown du BO, le rendu en page Article et le rendu en page ressource : 

![image](https://user-images.githubusercontent.com/39315/42633539-1539d620-85e1-11e8-8b3f-e75692ac1a61.png)

![image](https://user-images.githubusercontent.com/39315/42633554-231e04fa-85e1-11e8-8409-1e01caac0660.png)

![image](https://user-images.githubusercontent.com/39315/42633572-334fc822-85e1-11e8-89b5-a8dda2669467.png)
