### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#141]
En complément de #133 

Nous avons revu l'ensemble de la navigation du site. Plutôt que de renvoyer encore une version de la charte graphique. Voici les points à modifier : 

- [x] TopMenu abandonnée => le masquer sur toutes les pages où il aparaissait
- [x] SideMenu présent partout et simplifié => il reprend le footer mis bout à bout et vient par dessus la page (et non en la poussant comme c'est la cas actuellement)
![sidemenu](https://user-images.githubusercontent.com/8322713/42562823-0a0cccba-84fd-11e8-96bb-27e657c71f56.png)
- [x] 2 navbars en général : 1 static et 1 fixed (qui apparait après 70% du viewport scrollé). Mais des variantes selon : 
   -   couleurs => blanc avec fond transparent (STATIC) OU noir sur fond blanc (FIXED)
   -   selon breakpoint => desktop (bouton humburger et loupe placé à l'extérieur du container) OU mobile (bouton décalé de 16px du body)
   -   selon le contenu central => logo OU ArticleTitle OU TopicName

**En résumé sur les navabars :** 

-   **la Static est la même sur toutes les pages (textes et logo blanc + fond transparent)**
-   **la Fixed diffère selon les pages :** 
   + HomePage, AboutPage, RessourcePage => Fixed + logo + link HomePage
   + TopicPage => Fixed + TopicName
   + ArticlePage => Fixed + ArticleTitle
   + FocusPage => Fixed + FocusTitle

![navbar-fixed-article](https://user-images.githubusercontent.com/8322713/42565134-f0caa30c-8502-11e8-8bc1-8d03ab992c08.png)
![navbar-fixed-topic](https://user-images.githubusercontent.com/8322713/42565224-26a1f49e-8503-11e8-8cee-1d96cd9952dc.png)

Position des boutons juste à l'extérieur du body si breakpoint Desktop
![navbar-static](https://user-images.githubusercontent.com/8322713/42565284-4f8a5504-8503-11e8-8d76-47998a0188b9.png)

**Comment by Delapouite** [comment]
Le TopMenu avait demandé pas mal de boulot pour rendre les ouvertures et ordre de tabulation résultant accessible.

Comme vu dans ce commit : https://github.com/AtelierCartographie/eatlas/commit/b184b72c10f8db5cdc0cce455fab2dc59ad14544#diff-19e69feca8ab2f9171e35ca8bfca183bR128 il est dans l'immédiat facilement désactivable avec le bouleen passé en props du component Body. Au final il faudra bien entendu le retirer entièrement.

Pour le SideMenu, c'était lui qui de mémoire justifiait l'inclusion de l'extension [BootStrap Jasny](http://www.jasny.net/bootstrap/components/#navmenu) qui devrait donc devenir obsolète et déguerpir en échange d'un component maison.

**Comment by Delapouite** [comment]
TopMenu desactivé pour les TopicPages dans https://github.com/AtelierCartographie/eatlas/commit/3e2b46f058fc83a8cc3138fa451fadce5173e668
