### ISSUE TITLE
BO - parser - support des span noirs superflus

### ISSUE THREAD

**Issue by Delapouite** [AtelierCartographie/eatlas#143]
Voici deux extraits. Le premier est un "vieux" doc (les guerres de l'eau):

`<p><a id="_gjdgxs"></a>Les guerres de l’eau</p><p>En février 2013, le délégué <em>égyptien</em> s’est ainsi prononcé au<a href="http://www.un.org/fr/sc/"> </a><a href="http://www.un.org/fr/sc/"><span style="color: #1155cc">Conseil de sécurité de l’ONU</span></a> : « La sécheresse et la désertification <strong>croissantes</strong> aggravent définitivement les causes de conflit au Sahel. Le Moyen-Orient, l'autre région à laquelle l'Égypte appartient, est le lieu le plus pauvre en eau de la planète.…`

Le nouveau document (0A03) est couvert de "span" invisibles de couleur noir (#000000):

`<p><a id="_9vodzyl1yhqe"></a>Représenter l’espace mondial</p><p><span style="color: #000000">N</span>i<span style="color: #000000"> objectives ni exhaustives, les cartes ne sont qu’une interprétation du réel. Leur réalisation résulte d’une suite de choix, de lectures subjectives, d’une manière de voir, parfois de manipulation, souvent d’approximation. Ces images graphiques doivent permettre une perception instantanée et une mémorisation facile de l’information représentée ; leur efficacité s’appuie sur les règles de la </span><span style="color: #ff0000">sémiologie graphique</span><span style="color: #000000">. Des habitudes de représentation d’une </span><span style="color: #ff0000">géographie</span><span style="color: #000000"> traditionnelle ne fonctionnent plus pour cartographier l’espace mondial, qu’il s’agisse de l’orientation au nord, du centrage sur l’Europe, de l’inexistence du Pacifique traditionnellement coupé en deux, ou des limites convenues.</span></p>…`

A chaque fois qu'un document est uploadé sur eAtlas on sauvegarde la matière "brute" pour l'inclure dans EslasticSearch à des fin de rechercher et on sauvegarde aussi sa structure pour la restitution HTML.
Cela explique pourquoi coté Back Office on voit correctement les données brutes, mais qu'une fois rendu on ne voit que la lettre "i" (du mot "Ni") qui pour une raison qui m'échappe est le seul enfant direct du paragraphe.

**Comment by naholyr** [comment]
Ce problème est-il toujours d'actualité ou a-t-il pu être adressé par un reformatage des documents ?

**Comment by TomBor** [comment]
Nous reformatons les textes en amont.
