### ISSUE TITLE
Fonctionnalités SEO pour le front

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#147]
Lors de la génération du site, il faut inclure les éléments nécessaires à un bon référencement :

* [x] Méta dans les pages
* [x] URL unique propre et stable
* [x] Génération du `sitemap.xml`
* [x] Génération du `robots.txt` (@delphinelrcl quel contenu ?)
* Gestion de la 404 :
  * [x] Génération d'une page fixe
  * [x] Configuration du serveur HTTP
* Analytics :
  * À confirmer : utilisation de Google Analytics ou d'un autre service ?
  * [x] Ajout d'une option de configuration côté serveur (le code Google Analytics) pour l'ajout des tags dans les pages
    - Note : prévoir que cette option soit un tableau, et que dans chaque item soit inclus la plateforme ciblée (dans un premier temps on n'aura que l'option "google") afin de permettre l'ajout ou le changement de plateforme analytics dans le futur (le besoin de se détacher de Google peut être important)
  * [x] Configuration du compte Google Analytics côté SPO

**Comment by antoinerio** [comment]
- Le contenu souhaité de la page 404 est dans [la charte graphique](https://drive.google.com/file/d/1nb1N4xCFvbWSNWq2MK4joX8fiFAcXntq/view?usp=sharing)
Cette page 404 contient un lien vers notre formulaire de contact : https://goo.gl/forms/ei1BDbWq7CDQmwfL2

- Analytics
On utilisera Google Analytics. Pour la configuration, @jri-sp , pourrais-tu nous aider ? Il me semble que ScPo centralise tous les comptes analytics et attribue des droits ensuite, ce qui est le cas pour nos sites à l'Atelier de cartographie. Merci !

**Comment by naholyr** [comment]
Pour la configuration vous aurez simplement un numéro de compte dont vous devez disposer quelque part dans vos docs interne qu'il faudra reporter dans la config JSON, @jri-sp saura faire sans souci dans la continuité des autres options.

Cette partie sera implémentée la semaine prochaine a priori.

**Comment by antoinerio** [comment]
Bien noté ! Merci

**Comment by naholyr** [comment]
Ping @jri-sp pour la mise en place de la 404 j'ai tenté l'ajout d'une config nginx mais sans tester (je n'ai pas l'archi complète en local), à vérifier dans le commit c31e8dc

**Comment by naholyr** [comment]
Ajout de l'option de configuration ``analytics.google`` dont la valeur doit être le code du tracker GA (du genre ``UA-XXXXX-Y``). Par défaut cette option est ``null`` et le snipper n'apparaît pas. Une fois l'option définie, le snippet apparaît dans le ``<head>`` comme conseillé par la [documentation de Google Analytics](https://developers.google.com/analytics/devguides/collection/analyticsjs/), cf. e54a693

**Comment by naholyr** [comment]
Le snippet Google Analytics a été modifié conformément aux infos reçues par mail, le script est maintenant de cette forme :

```html
<script async src="https://www.googletagmanager.com/gtag/js?id=${code}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '${code}');
</script>
```

Le code est configurable toujours par l'option `analytics.google`

**Comment by jri-sp** [comment]
Ah désolé j'avais zappé de répondre...
Le commit https://github.com/AtelierCartographie/eatlas/commit/c31e8dc2c910b512561a241ef90a74d4ae8f7399 de @naholyr fonctionnera bien (sous réserve d'avoir généré au mois une fois le site).

**Comment by TomBor** [comment]
Pas grave. J'ai rétabli le commit de @naholyr, donc ça devrait être bon maintenant.
Merci
