### ISSUE TITLE
Sélection des mots-clé dans la recherche

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#148]
Une fois en production il y a plusieurs centaines de mot-clés, l'interface par liste de check-box n'est donc plus adaptée du tout.

Idée : utiliser un système d'auto-complétion type sélection de tag exemple ici https://selectize.github.io/selectize.js/

**Comment by antoinerio** [comment]
Oui, l'idée est d'afficher uniquement les 5 plus cités et faire suivre les autres mais en effet s'ils sont trop nombreux la solution que tu évoques semble être une bonne alternative.

**Comment by naholyr** [comment]
Voici le résultat implémenté :

![image](https://user-images.githubusercontent.com/214067/43327047-ad414144-91ba-11e8-84e3-b2bbd33cb602.png)

Pour info, limiter le nombre de mots-clé visible se fait très simplement en remettant la configuration `maxOptions: 5`, pour le moment je l'ai retirée et j'attends votre retour pour savoir si on limite réellement ou si on le laisse. L'intérêt de laisser concerne uniquement les visiteurs qui ne savent pas trop ce qu'ils cherchent et pourront naviguer dans les mots-clés, néanmoins pas sûr que ces utilisateurs trouvent un intérêt à une liste de 600 mots, mais ça indique au moins qu'il y a "plus". Je vous laisse juge :)
