### ISSUE TITLE
Page d'accueil responsive

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#149]
Actuellement la page d'accueil ne semble pas compatible mobile
![image](https://user-images.githubusercontent.com/214067/43205163-0936641e-9023-11e8-9a83-3b7d61643225.png)
Voir ce qui manque pour qu'elle soit responsive comme les pages internes

**Comment by naholyr** [comment]
Un fix à base de ``object-fit: cover`` a été mis en place, non compatible avec IE (résultat non testé). Devrait fonctionner avec Edge.
J'ai mis en place [un polyfill pour IE](https://github.com/jonathantneal/fitie), à vérifier.

**À noter** : quand on teste le responsive sous Chrome depuis les devtools, il y a un scroll horizontal dont je n'arrive pas à me débarrasser, et surtout que je ne reproduis pas quand je redimensionne la fenêtre ou que je teste sur mon smartphone. J'ai donc fini par l'ignorer.

**Comment by TomBor** [comment]
Merci.
Je ne sais pas si c'est lié mais maintenant la vidéo de la home page ne se lance pas.

**Comment by TomBor** [comment]
Je confirme, merci !
