### ISSUE TITLE
Backup: montée de version ES

### ISSUE THREAD

**Issue by jri-sp** [AtelierCartographie/eatlas#152]
Bonjour,

Est-ce que ça serait envisageable de passer ES en version 6.3.2 ? parce que depuis la 6.0.0  ils ont corrigé des bugs pour les snapshots, et ça me changerait la vie pour les backups de l'application.

(Ça serait bien aussi question failles de sécurité tout ça, tout ça).

Jérémy

**Comment by jri-sp** [comment]
Je peux aussi m'en sortir avec la 6.0.1, si jamais c'est pas possible.

**Comment by naholyr** [comment]
Je pense que le mieux est de faire le test, a priori on n'utilise rien de très pointu et s'ils respectent le semantic versioning on devrait être serein (il me semble que c'est le cas).

**Comment by jri-sp** [comment]
Merci pour ta réponse. J'ai testé en local sans données, puis avec les données de la PPRD ça semblait ok. Je le déploie en PPRD pour voir si ça apporte des problèmes.

**Comment by naholyr** [comment]
:+1:
