### ISSUE TITLE
Lexique : nombre max de définitions ?

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#153]
Le lexique final comporte 250 définitions.
L'erreur suivante apparait à l'import : 
>Erreur:[es_rejected_execution_exception] rejected execution of org.elasticsearch.transport.TransportService$7@33c97cfc on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@606811ca[Running, pool size = 2, active threads = 2, queued tasks = 199, completed tasks = 221]]

**Comment by naholyr** [comment]
A priori on ne doit pas avoir de nb max de définitions, mais je pense qu'avec le système de stockage global + individuel que j'avais mis en place il y a un nombre élevé de requêtes lancées en parallèle. La mise en place d'une file d'attente devrait corriger ça sans trop gêner les performances (et au pire c'est seulement lors de l'upload du lexique). Je devrais pouvoir corriger ça vendredi, est-il possible de m'envoyer le lexique final par mail ou sur le drive partagé afin de tester ?

**Comment by TomBor** [comment]
Maintenant que le nombre max de définition est réglé un autre problème survient !
On ne peut pas supprimer le lexique, cette erreur survient : 
> Unhandled Rejection (Error): Unknown Resource Id

Et un autre point sur la notation des alias. Si il n'y a qu'un seul alias, les deux notations fonctionnent (`{alias}: ["alias 1"]` et `{alias} alias 1`)
Mais à partir de deux alias, seule la première notation fonctionne.

**Comment by naholyr** [comment]
Devrait être corrigé par l'ajout d'une file d'attente (avec concurrence max fixée par défaut à 50 pour avoir de la marge par rapport aux 200 du serveur elastic search) par le commit  be7ad9d

**Comment by naholyr** [comment]
J'ai une autre erreur de mon côté, "cannot get property definitions" mais globalement l'application ne fonctionne effectivement pas du tout sans lexique. Je vais appliquer quelques garde-fous de ce côté.

Je regarde pour la syntaxe des alias.

**Comment by naholyr** [comment]
L'erreur `Unknown Resource Id` est une 404 normale si on essaie d'accéder à l'adresse d'une ressource non existante, mais je n'ai pas réussi à trouver de scénario où je tombe dessus. J'ai appliqué une correction évitant au "site builder" de planter quand il n'y a pas de lexique trouvé. Je ne sais pas si ça suffira. Si tu rencontres encore cette erreur pourrais-tu m'en dire plus sur les conditions ?

Je rouvre la #46 pour la gestion des alias sur plusieurs lignes

**Comment by TomBor** [comment]
Après test l'erreur à la suppression du lexique n'apparait plus.
Merci !
