### ISSUE TITLE
Google Drive Picker : accès aux Team Drives

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#156]
Est-ce possible d'accèder Team Drives (Drive d'équipe) depuis le picker ?
Si oui, est-ce simplement faisable ?

**Comment by naholyr** [comment]
Je n'ai pas eu beaucoup de succès, quand j'active les team drives l'onglet disparait tout simplement :(

![image](https://user-images.githubusercontent.com/214067/45228056-62747900-b2c2-11e8-92c5-5f87fd539e88.png)

Normalement il suffit d'ajouter quelques lignes pour inclure cette vue, mais ça ne fonctionne pas (du tout ;)) et je n'arrive pas à savoir si c'est un problème côté configuration de l'app Google ou bien une limitation de notre module `react-google-picker`.

Le guide à suivre est censé être celui-là : https://developers.google.com/drive/api/v3/enable-teamdrives

Tout se passe dans le fichier `DocPicker.js` dans le callback de création du picker où l'on a accès aux API standard Google, les lignes concernés sont en commentaires dans le commit 58ea61d :

- `docsView.setEnableTeamDrives(true)` est censé activer les team drives dans la vue "docs", c'est cette ligne qui fait disparaitre totalement la vue dès qu'elle est décommentée
- `.enableFeature(google.picker.Feature.SUPPORT_TEAM_DRIVES)` est normalement requis si on veut faire fonctionner la ligne du point précédent, mais elle ne semble pas avoir d'effet ici
- enfin, `docsView.setIncludeFolders(true)` n'est a priori pas liée mais je l'ai laissée quand-même, il s'agit d'inclure les sous-dossiers au lieu d'avoir uniquement les fichiers

J'ai pushé les lignes commentées afin que tu puisses tester de ton côté en les dé-commentant si ça fait quelque-chose de différent, car c'est peut-être lié aux paramètres de l'app Google qu'on a déclarée.

**Comment by TomBor** [comment]
Plus de succès de mon côté en dé-commentant les lignes concernées. Les drives d'équipe s'affichent bien dans un onglet mais une fois que l'on rentre dedans par double click, le picker ne trouve pas de contenu.
![in-team-drives](https://user-images.githubusercontent.com/8322713/45283690-dbe8b300-b4de-11e8-9f21-1f830ab7d8a7.png)
![team-drives](https://user-images.githubusercontent.com/8322713/45283691-dbe8b300-b4de-11e8-8545-92aea185f44f.png)

Comme ce n'est pas du tout prioritaire on peut laisser tomber pour le moment
