### ISSUE TITLE
Page ressource + carte - télécharger une image full alternative

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#157]
Concerne les pages ressources dans le cas d'une carte.
L'idée est de changer les fichiers à télécharger
![capture d ecran 2018-09-11 a 15 41 06](https://user-images.githubusercontent.com/8322713/45363956-2b130e80-b5d9-11e8-90c6-ccee4377e4ce.png)

Et de les remplacer par des images qui inclus le titre et la source en dur dans le jpeg, ce qui est plus utile pour une réutilisation en dehors du site eatlas.

Ces fichiers "full" sont déjà prêts. La différence avec les fichiers classiques (tronqués) est dans le nom (ajout de "-full" avant la densité): 

+   classique : `0C01-m-medium@1x.jpg`
+   full : `0C01-m-medium-full@1x.jpg`

Une solution plus simple serait de pouvoir charger en dur via ftp tous les images full et on interviens seulement dans RessourcePage.js pour changer les liens et (s'ils existent) pointer vers les fichiers full.

Une solution plus complexe serait de charger via le back office les fichiers classiques et full en même temps.

**Comment by naholyr** [comment]
Le serveur ayant un accès en lecture+écriture aux fichiers publics, il est capable de faire le test de l'existence d'un fichier avec suffix "-full" et d'utiliser celui-là à la place s'il existe, ça pourrait être mis en place assez facilement.

L'upload via back-office est aussi faisable : on a déjà "small", "large", "medium", on pourrait imaginer ajouter "full" mais il faudrait s'assurer qu'on ne l'inclut pas dans les images responsive 'n co. À tester. Dans ce cas le nom devrait plutôt être ``0C01-m-full@1x.jpg``.

**Comment by naholyr** [comment]
Ah non j'avais mal compris, il peut y avoir un "full" par taille de la même image/carte ? Dans ce cas la seconde option n'est pas la bonne. Ce serait un nouvel upload à imaginer (à voir si besoin d'un nouveau champ dans l'index ES mais pas sûr), à réfléchir. En attendant je peux facilement mettre an place la première option (upload manuel + vérification lors de la génération).

**Comment by TomBor** [comment]
Oui il y a autant de fichier full que de classique.

La première option est largement suffisante pour nous.

**Comment by TomBor** [comment]
Exemple de fichiers sur une carte, la 0C02 : 

**CLASSIQUE**
```
0C02-x-large@1x.jpg
0C02-x-large@2x.jpg
0C02-x-large@3x.jpg
0C02-x-medium@1x.jpg
0C02-x-medium@2x.jpg
0C02-x-medium@3x.jpg
0C02-x-small@1x.jpg
0C02-x-small@2x.jpg
0C02-x-small@3x.jpg
```
**FULL**

```
0C02-x-large-full@1x.jpg
0C02-x-large-full@2x.jpg
0C02-x-large-full@3x.jpg
0C02-x-medium-full@1x.jpg
0C02-x-medium-full@2x.jpg
0C02-x-medium-full@3x.jpg
0C02-x-small-full@1x.jpg
0C02-x-small-full@2x.jpg
0C02-x-small-full@3x.jpg
```

**Comment by naholyr** [comment]
Le support a été mis en place, par contre le fichier doit s'appeler ``…-full-1x.jpg`` (tiret au lieu de l'arobase). Ce n'est pas un blocage technique, et je peux le faire sauter si ça ne vous arrange pas, c'est plus par souci d'homogénéité avec les autres noms des fichiers uploadés où le serveur génère les densités avec un tiret (j'avais peur que l'arobase puisse avoir un effet secondaire dans une URL ou un chemin, comme c'est le séparateur d'authentification HTTP). Garder le "@" dans le fichier "full" me prendra 3 minutes, à vous de me dire :)

Note : dans les blocs de téléchargement je n'inclus qu'un seul fichier par taille, celui de densité la plus élevée. Faut-il inclure toutes les densités disponibles dans les téléchargements ?

**Comment by TomBor** [comment]
Top, merci beaucoup !
Le remplacement du "@" par un tiret n'est pas un problème de notre côté. On peut laisser comme ça.
Par contre je n'ai pas réussi à tester, quel est la marche à suivre ?
Il faut uploader les fichiers côté serveur dans "server > data > uploads" ?

**Comment by TomBor** [comment]
up sur la marche à suivre pour que ça fonctionne.

**Comment by naholyr** [comment]
Oui il faut uploader dans ce dossier et normalement à la prochaine
publication ils seront pris en compte.

Le jeu. 13 sept. 2018 à 16:36, Thomas Ansart <notifications@github.com> a
écrit :

**Comment by antoinerio** [comment]
Sur cette même page ressource, un "undefined" apparaît lorsque le champs "sources" est vierge.
Est-ce possible de le masquer ?
<img width="1712" alt="capture d ecran 2018-09-17 a 11 36 40" src="https://user-images.githubusercontent.com/16940767/45615993-66e12480-ba6e-11e8-8095-d245fa57c704.png">
Merci !

**Comment by TomBor** [comment]
J'ai essayé la procédure suivante en local sans succès.

1. Uploader via le backoffice une carte (id 2C20)
2. Déposer directement dans le dossier 'server>data>uploads' les versions full avec la bon nommage "map-2C20-small-full-1x.jpg"
3. Publier la carte dans le backoffice (pour déclencher la copie des médias vers la partie public)
4. Tester le téléchargement depuis la page ressource public de la carte => sans succès la version classique s'affiche
(en local les fichiers full n'ont pas été copiés dans la partie public 'client>public>generated>media')
(idem manuellement avec 'yarn rebuild-site')

**Comment by naholyr** [comment]
> Sur cette même page ressource, un "undefined" apparaît lorsque le champs "sources" est vierge.
> Est-ce possible de le masquer ?

C'est vrai aussi pour le copyright, je l'ai fait sur la branche i18n je vais vérifier si c'est mergé sur master

> J'ai essayé la procédure suivante en local sans succès.

Je revérifie en local pour voir ce qui cloche

**Comment by naholyr** [comment]
@TomBor en local j'ai retesté en faisant attention au processus et j'ai levé quelques zones de confusion possible :

- dans la page ressource les liens de téléchargement sont limités à **la plus haute résolution disponible**(pas la peine d'ajouter un "large-full-1x" s'il y a un "large-3x", il sera simplement inutilisé, mais copié quand-même normalement)
- l'extension après upload est renommée en ".jpeg" (sûrement lié à notre module de types mime) donc le fichier doit s'appeler "large-3x.jp**e**g"

Voici le procédure suivie qui fonctionne :

- Création de la ressource "carte" en envoyant les fichiers ``0C02-{large,medium,small}@{1,2,3}x.jpg``
- Publication de la ressource, le lien de téléchargement "version détaillée" est :
  - ``http://localhost:4000/resources/0C02/file/large-3x``
  - ``http://localhost:3000/generated/media/map-0C02-large-3x.jpeg`` dans generated
- J'ajoute le fichier ``server/data/uploads/map-0C02-large-full-3x.jpeg``
- Je relance la génération du site, le même lien devient :
  - ``http://localhost:4000/resources/0C02/file/full-large-3x`` en preview
  - ``http://localhost:3000/generated/media/map-0C02-large-full-3x.jpeg`` dans generated

Ça télécharge bien le bon fichier. Si j'ajoute le fichier ``server/data/uploads/map-0C02-large-full-2x.jpeg``, après régénération du site le fichier ``http://localhost:3000/generated/media/map-0C02-large-full-2x.jpeg`` existera bien mais il n'y aura pas de lien vers celui-ci dans la fiche.

J'ajoute une section dans la doc à ce sujet.

**Comment by naholyr** [comment]
Doc mise à jour, je te laisserai compléter l'issue en fonction des résultats de tes propres tests.

@antoinerio le défaut d'affichage a été corrigé en passant (cf. 01fe9d6)

**Comment by TomBor** [comment]
Fonctionne parfaitement en prod.
Merci !
