### ISSUE TITLE
Ordre articles et navigation entre articles

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#162]
Deux problèmes : 

* Dans les pages de topic, l'ordre des articles ne suit pas l'ordre des identifiants.
* Dans un article, les flèches de navigation flottante et les boutons préc./suivant en bas d'article ne suivent pas du tout l'ordre des identifiants et donc du livre

Tu peux t'en rendre compte avec ton accès à la prod

**Comment by TomBor** [comment]
Corrigé avec https://github.com/AtelierCartographie/eatlas/commit/dd4d8673968786ce4c1141c50c739e56b152cb80

**Comment by TomBor** [comment]
En preview c'est bien corrigé, mais en public l'ordre est de nouveau plus fait selon l'identifiant.

**Comment by naholyr** [comment]
Ce dernier point me fait penser que c'est un problème de génération, serait-il possible de faire les tests suivants avec le support de @jri-sp ?

- lancer la commande ``yarn rebuild-site`` et me fournir son output (on devrait y voir listées les pages générées, notamment celles des topics, je veux vérifier ça)
- vérifier si après ça c'est toujours dans le mauvais ordre
- si c'est toujours buggé, vider le dossier ``generated`` et relancer la commande, et revérifier

**Comment by jri-sp** [comment]
Hello,
Le log du premier point: [rebuild-site.log](https://github.com/AtelierCartographie/eatlas/files/2442286/rebuild-site.log)
Je vous laisser vérifier et me dire si je fais le reste...

**Comment by TomBor** [comment]
Merci Jérémy !
Pas de changement de mon côté (avec une actualisation forcée + vider le cache).
@jri-sp Tu peux continuer le reste du coup.

**Comment by jri-sp** [comment]
C'est fait pour le point 3

**Comment by naholyr** [comment]
OK je trouve bien dans les logs la regénération du fichier ``/eatlas/data/uploads/public/generated/rubrique-contrastes-et-inegalites.html``, sur la page https://espace-mondial-atlas.sciencespo.fr/rubrique-contrastes-et-inegalites.html je vois le header ``Date: Wed, 03 Oct 2018 14:16:30 GMT`` donc je pense qu'on peut vraiment éliminer le cache. Damned!

Je regarderai si je reproduis en local. A priori pas la peine d'en faire plus pour le diagnostic pour le moment.

Merci beaucoup pour ta réactivité @jri-sp !

**Comment by naholyr** [comment]
Bonne nouvelle : le bug est reproduit localement, en preview c'est OK mais en build on a l'ordre d'insertion (il s'avère qu'en local je n'avais pas de différence car j'avais inséré les articles dans le bon ordre lors de la saisie…). Correction en cours.

**Comment by TomBor** [comment]
👍

**Comment by naholyr** [comment]
Le bug devrait être corrigé : attention avant de passer en prod vu qu'il y a pas mal de commits du #145 il faudra bien faire le tour du site pour s'assurer qu'il n'y a pas eu de régression lors des modifications.

Si jamais c'est un no-go :
- soit c'est assez rapide et je corrige les commits fautifs du #145 sur ``master``
- soit c'est compliqué et alors
  - soit on attend la fin du #145 (compter jeudi prochain max)
  - soit on *cherry-pick* les commits qui nous intéressent

**Comment by TomBor** [comment]
Merci @naholyr !

@jri-sp la branche 'staging' est à jour avec la correction du bug. Peux-tu relancer la pprd pour que l'on teste ? Merci.

**Comment by jri-sp** [comment]
C'est fait

Le jeu. 4 oct. 2018 à 16:56, Thomas Ansart <notifications@github.com> a
écrit :

**Comment by TomBor** [comment]
Merci @jri-sp !

@naholyr C'est presque bon, maintenant les topics sont en trie descendants (6,5,4...) voir footer, side-menu et homepage. Mais ça doit juste être cette [clé de trie à inverser](https://github.com/AtelierCartographie/eatlas/commit/385d6f5de76e42cb4e6bfc5f4e60eafa49144869#diff-83a6a4cda74b018d5586fee91c1510aeR84)

![capture d ecran 2018-10-04 a 17 31 59](https://user-images.githubusercontent.com/8322713/46485167-7779f480-c7fb-11e8-9278-5088bff527b5.png)

**Comment by TomBor** [comment]
@jri-sp Peux-t-on tester que ce bug est bien corrigé en pprd ? Comme ça on pourra le basculer rapidement en prod. Merci d'avance !

**Comment by jri-sp** [comment]
Bonjour, c'est fait pour la pprd

**Comment by TomBor** [comment]
Merci @jri-sp ! Ça fonctionne bien alors j'ai fait push en prod. À mettre à jour aussi du coup et on est tranquille pour aujourd'hui !
