### ISSUE TITLE
Page ressource - article ou focus lié pas d'image

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#164]
Dans une page ressource d'une carte la section 'article ou focus lié' n'affiche pas la vignette de l'image header.
![capture d ecran 2018-09-27 a 12 05 03](https://user-images.githubusercontent.com/8322713/46138995-b59c7480-c24d-11e8-8f86-d017c4d21ed8.png)

Pour le type image, la section ne s'affiche pas du tout. Exemple avec une photo d'image header, on devrait voir sous 'Article ou focus lié' le lien vers l'article qui utilise cette image header.

**Comment by naholyr** [comment]
J'ajoute que le lien est cassé également, sûrement une donnée mal chargée comme pour le bug précédent sur les liens de footer.
![image](https://user-images.githubusercontent.com/214067/46396357-82dff980-c6ef-11e8-84b2-6b26e5d9b96e.png)

**Comment by naholyr** [comment]
À valider pour fermeture

**Comment by TomBor** [comment]
Merci les liens fonctionnent ! J'ai juste changer la classe css de la div de l'image pour qu'elle apparaisse bien.
