### ISSUE TITLE
url ressource depuis page article ou focus

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#165]
Depuis une page article, les liens via le footer ou le menu vers les ressources (cartes et graphiques, photos, lexique) ne fonctionnent pas.

ex : https://espace-mondial-atlas.sciencespo.fr/rubrique-contrastes-et-inegalites/recherche.html?types%5B%5D=map
Les liens se rajoutent à la rubrique au lieu de le remplacer
https://espace-mondial-atlas.sciencespo.fr/recherche.html?types%5B%5D=map (fonctionne)

**Comment by naholyr** [comment]
Le dernier commit consiste à rendre absolu tous les liens vers les "pages globales" (lexique, mentions légales, etc) et les pages de recherche, ce qui devrait corriger ce problème.
