### ISSUE TITLE
Update ressource => erreur EACCESS

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#166]
Voici l'erreur en prod : 
>Erreur: Failed to update files on (un)publishing: EACCES: permission denied, unlink '/eatlas/data/uploads/public/generated/media/image-6P10-small-3x.jpeg'

En pprd pas de problème rencontré

**Comment by jri-sp** [comment]
Oui, j'ai modifié les droits. Est-ce que ça fonctionne maintenant ?

**Comment by TomBor** [comment]
Parfaitement !
Merci beaucoup !
