### ISSUE TITLE
Import docx

### ISSUE THREAD

**Issue by annelhote** [AtelierCartographie/eatlas#17]
- [x] Quel est le dossier Drive ouvert par défaut par le Google Picker ?
- [x] API non sécurisée, j'imagine que çe ne sera plus le cas pour la prod ?
- [x] Erreur 500 lors de mon text d'import
- [x] Sur la page "upload" (http://localhost:3000/upload), renommer le bouton "picker" en "Importer"
- [x] Dans le menu, renommer "envoi"par "Import"

**Comment by naholyr** [comment]
- Il n'y a pas de dossier spécifique ouvert par défaut, aucune option modifiée de ce côté là, avez-vous une préférence ?
- Oui, HTTPS requis pour la prod (cf. #12)
