### ISSUE TITLE
Etude performance front

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#170]
- Voir pourquoi on charge bootstrap en front
- Autres pistes ?

**Comment by naholyr** [comment]
# Poids des ressources

Première étape, réduire le poids des ressources

## Ressources chargées par poids

Exemple de la page de recherche (je n'ai inclus que les ressources ≥ 10 KB, les autres étant relativement négligeables) :

- jquery.min.js  29.2 KB
- google tag manager (chargé par google analytics) 29.2 KB
- lodash.min.js  24.6 KB
- va9B4kDNxMZdWfMOD5VnLK3eRhf6.woff2 (font "fira sans") 21.6 KB
- va9E4kDNxMZdWfMOD5Vvl4jL.woff2 (font "fira sans") 20.8 KB
- bootstrap.min.css 17.9 KB
- analytics.js 17.1 KB
- selectize.min.js  14.7 KB | 162 ms
- bootstrap.min.js  9.4 KB

Pour un poids total de 230 Kb.

Sur une page article on rajoute encore 60 KB de fonts (ajout de "gentium basic" et des "glyphicons" de bootstrap) pour un poids total de 310 KB (l'html est plus lourd + les images de l'article etc… pour le reste ce sont les même ressources).

## Pistes d'amélioration

- **Build custom de jQuery** : en listant les fonctionnalités réellement utilisées, j'ai pu obtenir un build de jQuery de 22.1 KB (1)
  - On a aussi simplement le build officiel "slim" qui garantit une plus faible maintenance et qui pèse 23.2 KB, moyennant la réécriture de l'appel Ajax de la recherche on gagne déjà 6 KB
- **Build custom de Lodash** : en listant les fonctionnalités réellement utilisées, j'ai pu obtenir un build de 4.6 KB (2)
  - Ici le coût en maintenance est bien plus faible (une seule commande) et le gain énorme : 20 KB de gain immédiat
  - En ajoutant ``_.each`` on double le poids du build, c'est pourquoi il était plus intéressant d'écrire une boucle for standard dans la page de recherche pour économiser ces 4 KB
- **Web fonts** : pas grand-chose à faire sans sacrifice sur la charte graphique
  - À part les fonts "glyphicons" chargées dans la page article, qui ne servent en réalité qu'à afficher les flêches "précédent/suivant" alors qu'elles pèsent 18 KB !! On pourrait remplacer ces icones par des images SVG et gagner probablement 17 KB
- **Analytics** : 50 KB à gagner mais au prix de l'analytics
- **bootstrap** : on utilise les CSS et le JS pour le menu ouvrant (incluant "jasny") je pense qu'on peut gagner quelques KB car on n'utilise qu'un seul composant, je n'ai pas encore vu comment faire un "build custom"
- **selectize** : utilisé sur la page de recherche pour les mots-clés, on pourrait n'inclure ce script que dans la page de recherche pour éviter de faire charger 15 KB aux visiteurs n'en ayant pas besoin

## Annexes

### (1) build jquery

```
Modules as of 3.3.1 (see https://github.com/jquery/jquery#modules), checked if required by eatlas:

[ ] ajax
[ ] ajax/xhr
[ ] ajax/script
[ ] ajax/jsonp
[x] css
[x] css/showHide (used by selectize)
[ ] deprecated
[x] dimensions
[ ] effects
[x] event
[ ] event/alias
[ ] event/focusin
[x] event/trigger (used by selectize)
[x] offset
[ ] wrap
[ ] core/ready
[ ] deferred
[x] exports/global
[ ] exports/amd

Commands used to build:

git clone git@github.com:jquery/jquery.git
cd jquery
git checkout 3.3.1
npm install
npm run build
npx grunt custom:-ajax,-deprecated,-effects,-event/alias,-event/focusin,-wrap-core/ready,-deferred,-exports/amd uglify:all
```

### (2) build lodash

```
npx lodash-cli include=throttle,template exports=global -p -o client/public/assets/js/lodash.custom.min.js
```

**Comment by naholyr** [comment]
On a déjà un gain de 55 KB sur la page de recherche soit 24% ; et 40 KB (voire près de 60 KB en se débarrassant de la font "glyphicons", soit ~20%).

Côté poids, seul la suppression de la font "glyphicons" est encore une piste intéressante, aller plus loin prendrait sans doute trop de temps pour le gain.

**Comment by TomBor** [comment]
Merci @naholyr pour cette amélioration significative de performance !

Dans l'archive suivante, j'ai dessiné des flèches en svg (140 octets par flèche) pour remplacer les icones existantes.
[arrows-svg.zip](https://github.com/AtelierCartographie/eatlas/files/2472386/arrows-svg.zip)

**Comment by naholyr** [comment]
Ah zut on s'est croisé je les ai dessinées de mon côté et j'ai du prendre 100 fois plus de temps que toi ^^ je remplace par les tiennes

**Comment by TomBor** [comment]
Désolé, je n'ai vu tes messages que ce matin tard.
