### ISSUE TITLE
Section Lexicon sur mobile trop large

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#173]
Sur mobile, l'affichage d'un article se fait sur une largeur plus grande que celle du viewport.
Cela vient de la partie des définitions en bleu qui est plus large que le conteneur.
Lorsque l'on simule un mobile avec la devtools de chrome, on s'en rend compte.
![capture d ecran 2018-10-12 a 11 27 45](https://user-images.githubusercontent.com/8322713/46861030-efef3f80-ce11-11e8-976e-d0202874e5f4.png)

**Comment by naholyr** [comment]
Pour info quand je supprime carrément le tag "section.Lexicon"
![image](https://user-images.githubusercontent.com/214067/46876540-e16b4d00-ce3e-11e8-8f29-cd20c21387ed.png)
Il doit donc y avoir encore autre chose

**Comment by naholyr** [comment]
Dans mon cas c'était la zone "article suivant" dont le texte dépassait à droite

**Comment by naholyr** [comment]
En ciblant le "prev/next" en bas d'article j'ai un bon résultat en local :
![image](https://user-images.githubusercontent.com/214067/46876979-f694ab80-ce3f-11e8-919a-d4cc76e25bcf.png)
Je vous laisse tester avec le dernier commit

**Comment by TomBor** [comment]
Bien vu ! Merci.
Maintenant plus rien de dépasse.
