### ISSUE TITLE
Accès site impossible via wifi eduroam

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#175]
@jri-sp 
1. En dehors de Sciences Po, le site présente une erreur car il ne peut accéder à ce fichier javascript : `/assets/js/eatlas.es5.js`

2. Apparemment le site fonctionne mal ou pas sur le réseau EDUROAM. On nous l'a signalé mais je ne l'ai pas encore testé

**Comment by TomBor** [comment]
MAJ
Le premier point est réglé depuis longtemps.
Par contre le second persiste bien, je viens de faire le teste en me connectant au wifi EDUROAM, et impossible d'accéder au site de l'eatlas.
![capture d ecran 2018-11-07 a 13 37 48](https://user-images.githubusercontent.com/8322713/48132087-92280900-e292-11e8-95f4-79c270dc0566.png)

@jri-sp Est-ce que tu connais les spécificités de ce réseau wifi ou quelqu'un à ScPo qui pourrait nous aider sur ce sujet ?

**Comment by jri-sp** [comment]
On travaille dessus mais ce n'est pas trivial comme problème à régler

**Comment by jri-sp** [comment]
C'est résolu pour le point 2

**Comment by TomBor** [comment]
Bravo et merci !
