### ISSUE TITLE
TopicPage si absence de résumé

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#178]
Normalement si la rubrique n'a pas de résumé, la section entière ne s'affiche pas.

Or si la rubrique à eu une description mais que plus tard le texte du champs description à été supprimé dans le backoffice, la section `Summaries` reste présente tout en étant vide. C'est comme si le champs gardait la trace de la présence d'un ancien texte.
![capture d ecran 2018-10-24 a 15 06 28](https://user-images.githubusercontent.com/8322713/47432430-67bc5300-d79e-11e8-880c-fec356fbdf6f.png)

Il faudrait donc : 
+ que ce cas de figure du champs description effacé après avoir été remplie soit pris en compte
+ et que la page de rubrique concernée soit bien regénérée. Actuellement en production, rien ne se passe. Le site ne parait pas être regénérer par ce changement.

**Comment by naholyr** [comment]
Note : normalement on gère déjà le cas "ne pas afficher si vide", la piste serait donc que le contenu est ``<p></p>``, à tester

**Comment by TomBor** [comment]
Dans le cas dont je parlais où seule le titre résumé s'affiche, il y a bien une balise <p> présente et vide.

**Comment by TomBor** [comment]
À défaut d'avoir réussi à tester si il y avait une balise vide `<p></p>`, j'ai tester le cas où la longueur de _summaries_ est inférieur à 10 caractères.
