### ISSUE TITLE
Amélioration du moteur de recherche

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#182]
- [x] Trie par pertinence seulement = baisser le lexique = changer la valeur du boost de "single-definition". Après test, si '1', le lexique ce mélange aux autres résultats si '0.5' le lexique est rétrogradé.

- [x] Régler le fuzziness du moteur. Actuellement avec 'auto' produit des résultats étrange comme "presse" qui renvoie "richesse", "guerre" renvoie "endiGUER". En forçant la valeur de fuzziness à '1', on supprime ce problème mais on s'arrête à un seul caractère de différent.

- [x] Supprimer les références des résultats

- [x] Facettes : supprimer/masquer les filtres "mots-clés" et "Date de publication

- [x] Facettes : ajouter/afficher un filtre "Type" selon article, focus, carte, photo...

- [ ] [Elastic search highlighting](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/search-request-highlighting.html) : dans les résultats de recherche envoie le résultat trouver dans son contexte. Exemple : une phrase d'un article avec le mot mis en surbrillance

- [ ] Activer l'auto completion avec la fonctionnalité [completion suggester](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/search-suggesters-completion.html) de ES

**Comment by TomBor** [comment]
On peut considérer que les deux premiers points se règle en config. À tester en prod sur tout le contenu avec pour le moment un boost neutre des définition à '1' et une valeur de fuzziness forcée à '1'.

**Comment by naholyr** [comment]
:+1: je pense pouvoir m'occuper des poins 3,4,5 dans le lot en cours, en revanche les deux derniers points demanderont beaucoup plus de travail. À suivre…

**Comment by naholyr** [comment]
C'est OK pour les références et les facettes.

Note : comme il y a un titre spécifique lorsqu'on ne coche qu'un seul type (pour les pages de type "ressources" du footer), j'avais deux options 1. ajouter un query parameter à ces pages pour activer ce titre uniquement ici, ou 2. le gérer dans tous les cas.
Je suis parti sur l'option 2 et par cohérence j'ai du coup affiché ce titre dans tous les cas, incluant donc un cas "Tous" (cf. 6aaa2ae). S'il faut modifier ce comportement je peux m'en occuper avant mercredi.

**Comment by TomBor** [comment]
C'est bien avec le titre "Tous types".

Par contre en local, j'ai cette erreur lorsque je fait une recherche : 
`Uncaught TypeError: $(...).selectize is not a function
    at eatlas.es5.js:317
    at eatlas.es5.js:399`
Et ce message qui s'affiche à la place des résultats
![capture d ecran 2018-10-30 a 09 56 09](https://user-images.githubusercontent.com/8322713/47706667-1bec2c80-dc2a-11e8-8e78-16407bc9367c.png)

**Comment by TomBor** [comment]
@naholyr en suivant l'erreur de la console j'ai temporairement commenté les lignes 306 à 3011 de eatlas.js. Voir 20ea7df. Et alors les résultats du moteur s'affichent à nouveau en toutes circonstances. Je te laisse voir si ce fix est à reprendre en fonction de la cause réelle du problème.
```
// Enable auto-complete for keywords
    $('select.keywords').selectize({
      create: false,
      highlight: true,
      dropdownParent: 'body',
      //maxOptions: 5,
    })
```

@jri-sp un nouveau déploiement en prod est nécessaire. Merci encore de ta réactivité !

**Comment by jri-sp** [comment]
C'est déployé

**Comment by naholyr** [comment]
Merci Thomas c'était un oubli et commenter ces lignes est correct :
selectize n'était utilisé que pour les mots clé et j'avais du coup supprimé
la dépendance à la librairie sans retester correctement derrière, désolé
