### ISSUE TITLE
Lexique (en) - upload impossible

### ISSUE THREAD

**Issue by antoinerio** [AtelierCartographie/eatlas#186]
Impossible d'uploader le lexique en anglais > le type "lexique" n'apparaît pas dans la liste déroulante.

**Comment by naholyr** [comment]
Le blocage venait bien du calcul de la possibilité d'ajouter ou non, une fois les boutons "autorisés" on peut correctement uploader. Le reste suit bien, les articles en anglais vont bien chercher les définitions dans la ressource `LEXIC-EN`

**Comment by delphinelrcl** [comment]
le lexique FR ne s'affiche pas sur le FO. De même, il n'est pas possible d'importer le lexique EN depuis le bouton "ajouter une ressource". Le type "lexique" n'est pas disponible parmi la liste proposée.
Pour importer le lexique EN depuis le BO, il faut d'abord afficher sur le tableau de bord le lexique FR et ensuite cliquer sur le bouton "ajouter".

**Comment by naholyr** [comment]
Effectivement je n'avais corrigé que le chemin passant d'abord par le filtrage par type. J'ai corrigé également pour le chemin général, en générant correctement l'identifiant au passage.

Pour l'affichage du lexique en FO, **peux-tu préciser ?**

En local j'ai bien vérifié les points suivants :
- Affichage de la bonne liste de définitions (dans `/en/lexicon.html` et `/fr/lexique.html`)
- Affichage des bonnes définitions dans un articles FR et EN
- En preview (`http://localhost:4000/preview/definition?lang=fr`), mais aussi dans la version générée (`http://localhost:3000/generated/fr/lexique.html` après `yarn rebuild-site`)

À vérifier : les lexiques devraient avoir un identifiant formaté de manière très spécifique `LEXIC-EN` et `LEXIC-FR`, est-ce bien le cas ?
![image](https://user-images.githubusercontent.com/214067/62368894-3e4f0580-b52e-11e9-94bb-238c22b47e6b.png)
J'ai vu dans mes dernières corrections qu'il était possible d'avoir un identifiant mal généré, dans ce cas les définitions ne seront pas trouvées par le système. Il devrait suffire de supprimer l'ancien lexique et de le recréer en vérifiant que ça génère bien le bon ID.
