### ISSUE TITLE
Cartes & Focus (en) - Reconnaissance des ID dans les docx

### ISSUE THREAD

**Issue by antoinerio** [AtelierCartographie/eatlas#187]
Lorsqu'on upload un article EN, les cartes et graphiques, ainsi que les focus, ne sont pas reconnus en EN et donc attribués automatiquement aux ressources FR
 Les “-EN” présents dans les ID dans les docx, ne sont pas correctement reconnus.

**Comment by TomBor** [comment]
Il y a un vrai problème sur la reconnaissance des identifiant + langue des ressources après parsing des articles (docx).

Cela fonctionne bien pour les photos mais pas pour les cartes et focus où le tiret de ID-EN sert de séparateur.
En l'état tout nos derniers imports d'articles sont à jeter car les ID de ressources ne sont pas bien reconnues.

@naholyr Est-ce que ça peut se corriger facilement et rapidement ?

![Capture d’écran 2019-07-05 à 15 23 44](https://user-images.githubusercontent.com/8322713/60725307-05c10980-9f39-11e9-9c67-b1ac9f12a151.png)

**Comment by naholyr** [comment]
Bonjour, vu, je regarde lundi midi pour donner un avis. Si c'est possible
je tâcherai de le corriger d'ici mercredi. Y a-t-il beaucoup d'imports
concernés ? Il peut être possible de faire un script de correction des
contenus importés pour n pas avoir à les refaire, ça peut valoir le coup
s'il y en a un grand nombre.

Le ven. 5 juil. 2019 à 15:34, Thomas Ansart <notifications@github.com> a
écrit :

**Comment by TomBor** [comment]
Bonjour Nicolas,
Merci. Ça concerne une quarantaine d'imports (environ 30 articles et 10 focus). Rien d'insurmontable, à toi de voir si un script vaut la peine (le temps que tu passes à le préparer contre le temps de ré-importer).

En tout cas je me pencherai sur ta solution car j'ai commencé à regarder de ce côté là mais sans succès : https://github.com/AtelierCartographie/eatlas/blob/master/server/lib/doc-parsers/article.js#L58

**Comment by naholyr** [comment]
J'ai contextualisé les commits à l'issue #190, le principal étant normalement https://github.com/AtelierCartographie/eatlas/commit/9502eb6 mais le problème ne venait pas réellement du parsing, plutôt de la façon dont on cherchait les ressources liées. En ajoutant un peu de contexte j'ai pu rendre cette méthode plus "intelligente".
