### ISSUE TITLE
Articles liés (voir aussi) - Reconnaissance des ID dans les docx

### ISSUE THREAD

**Issue by antoinerio** [AtelierCartographie/eatlas#190]
Lorsqu'on upload un article EN, les articles liés (voir aussi) ne sont pas reconnus en EN et donc attribués automatiquement aux article FR.
Par exemple, la reconnaissance des articles liés devrait se faire à partir ces métadonnées :
{Continuer dans l’Atlas}:
- 1A02-EN - Development
- 1A05-EN - Living and dying
- 1A08-EN - Competition for knowledge
- 2A04-EN - A Mobile World 
- 6A07-EN - Financial Regulation

**Comment by naholyr** [comment]
Bien vu, le principe devrait être (à vérifier ce qui manque pour que ça marche) :

- Si on fait référence à "1A02" dans un article "FR", ça doit être considéré comme "1A02-FR" (pas de fallback, on a pris la voie stricte) 
- Si on fait référence à "1A02-FR" ou "1A02-EN", pas de traitement sur l'ID on le prend tel quel

**Comment by naholyr** [comment]
Il manquait pas mal de tests pour mieux contextualiser la recherche des ressources. Au niveau de la saisie il y avait aussi un comportement parasite pénible (l'ajout de la langue à l'identifiant saisi, même lorsqu'on avait un identifiant forcé parce qu'on avait cliqué sur un bouton "créer") que j'ai pu corriger même si a priori il ne vous concernait pas (moi je réutilise des docx fr avec les mauvais id, du coup j'ai ce genre d'effet de bord).

J'ai testé les cas suivant :

- ``[4C01-EN - Budget des opérations de paix de l’ONU, 1946-2016]`` dans un article anglais → va chercher ``4C01-EN`` (ou ``4C01`` tout court avec language = "en"), ou bien demander la création de ``4C01-EN`` → OK
- ``[4C03-FR - Pays fournisseurs de troupes aux OMP de l'ONU, 2016]`` dans un article anglais → va bien chercher ``4C03-FR`` (ou ``4C03`` tout court avec language = "fr"), ou bien demander la création de ``4C03-FR`` → OK
- ``[4C04 - Opérations de paix des Nations Unies, 1948-2016 (graph)]``` dans un article anglais → va bien chercher ``4C04-EN`` (ou ``4C04`` tout court avec language = "en"), ou bien demander la création de ``4C04-EN` → OK

On devrait être bon :+1:

**Comment by TomBor** [comment]
Au niveau des cartes, cela fonctionne dans le cas où la balise est de la forme suivante :
`[4C01-EN - faux titre...]`
Mais le cas suivant plus simple ne marche pas : 
`[4C01-EN]`

Idem pour les focus.

**Comment by naholyr** [comment]
Vu, je le traite dans la journée (avec plus de certitude que pour la #196 ;))

**Comment by naholyr** [comment]
La logique de parsing a été modifiée, dans les exemples de docs avec lesquels je travaillais il n'y avait pas de tiret avant la description, du coup je n'avais pas vu ce cas. Les exemples suivant fonctionnent tous maintenant :

![image](https://user-images.githubusercontent.com/214067/66057361-dff7d080-e538-11e9-88f5-b8a791e1eef1.png)

**Comment by TomBor** [comment]
Bizarrement dans la version en production à jour, les cas de ressources cartes notées [0C00-EN] dans le word de l'article ne sont pas du tout reconnue. Alors que la version [0C00-EN - ] oui.
