### ISSUE TITLE
FO - recherche - ajouter une facette sur la langue

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#191]
Actuellement on a le type de document et la rubrique à laquelle il appartient. Avec l'arrivée de la version anglaise, il nous faut une nouvelle facette sur la langue.

**Comment by TomBor** [comment]
À voir si on préremplie le filtre en fonction de la langue sélectionner pour par défaut avoir des résultats qu'en français si on consulte en français (idem pour l'anglais).

**Comment by TomBor** [comment]
Par défaut filtrer sur la langue utilisée.

**Comment by naholyr** [comment]
Pour mémo, la situation actuelle est l'intégration des articles de toute langue :+1: 

![image](https://user-images.githubusercontent.com/214067/61376713-f8ddd780-a8a1-11e9-9f90-4d5c78be80ae.png)

De mémoire ce choix avait été fait en se disant que les recherches exprimées dans une langue ramèneraient majoritairement des résultats dans cette langue. Un filtre explicite est quand-même plus clair ;)

**Comment by naholyr** [comment]
À valider (le filtre avait déjà été implémenté en prévision, je n'ai fait que le réafficher et définir une valeur par défaut lors de la recherche)
