### ISSUE TITLE
FO - accessibilité : navigation au clavier

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#193]
Aucune prise de focus sur la croix de fermeture du menu de navigation.

Lorsqu’on ouvre une fiche auteur, il est impossible de revenir en arrière au clavier ; bien que cela soit possible via la touche echap (non bloquant). Il faut ajouter une croix pour pouvoir la fermer.

**Comment by naholyr** [comment]
Ces points sont normalement tous adressés par les commits récents commentés "a11y", à valider au prochain déploiement
