### ISSUE TITLE
FO : affichage des pages responsive

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#194]
Quand on consulte le site depuis un smartphone, les actions suivantes ne sont pas possibles :
- fermer une définition
- fermer la fiche d'un auteur (ajouter une croix)
- visualiser les filtres

Il faut également ajouter un lien pour faciliter le  retour en haut de la page.

Enfin, Il faut supprimer l'icône de la recherche sur les pages des résultats car cela fait doublon avec l'onglet déjà présent.

**Comment by naholyr** [comment]
Ces points sont normalement tous adressés par les commits récents commentés "a11y", à valider au prochain déploiement
