### ISSUE TITLE
FO : affichage des images header

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#195]
Quand on publie l'image header d'un article, celle-ci ne s'affiche pas toujours sur le FO ou sur la preview ; par contre, elle est bien visible sur la page de la rubrique.
exemple : Fleeing accross borders

**Comment by naholyr** [comment]
Je pense que c'est une histoire de résolution, peux-tu ajouter `nicolas@chambrier.fr` dans les utilisateurs de la preprod afin que je vérifie ?

Il y a de toute façon un bug car :

- pour le carousel on prend la première image dispo en `1x` (peu importe la taille, ce choix est peut-être bizarre d'ailleurs) avec la fonction `getFirstImageKey(…)`
- pour la page rubrique on utilise également la première image dispo parmi `small@1x`, `medium@1x` ou `large@1x` avec la fonction `articleHeaderImageUrl(…)`, ce qui devrait revenir au même que la situation précédente :/
- dans la page article, on utilise la même fonction que dans le point précédent

Il est étrange que le 2e cas soit différent des deux autres, je vais regarder du côté des options passées.

**Comment by delphinelrcl** [comment]
Je viens de t'ajouter : est ce que tu peux te connecter ? Je croyais qu'il fallait un compte gmail...

**Comment by naholyr** [comment]
Note : en profiter pour valider qu'on fait bien les bons choix, pour chacune des situations listées
