### ISSUE TITLE
FO : affichage de la date d'un article

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#199]
Depuis l'ajout d'un surlignage pour les titres des articles afin de renforcer le contraste de la page, la date de publication se trouve à la droite du titre ; or le titre doit se trouver en dessous du titre de l'article et centré.

**Comment by naholyr** [comment]
Note : à tester en breakpoint mobile

**Comment by naholyr** [comment]
J'ai tenté plusieurs pistes mais le *block* ou le *flex* ou même un display *table* apportaient tous des problème de largeur des éléments affichés. Au final j'ai opté pour une marge autour de la date : comme ça elle a moins de place disponible pour s'afficher (40% de la largeur) et revient forcément à la ligne. Le critère pour ce bug est la longueur du titre (qui peut changer avec le changement de police au breakpoint).

Titre long :

![image](https://user-images.githubusercontent.com/214067/66466817-9ef54400-ea83-11e9-8df3-847c712c304b.png)

Titre très court :

![image](https://user-images.githubusercontent.com/214067/66466483-0fe82c00-ea83-11e9-9195-d4bf16b0455f.png)

Titre d'une seule lettre :

![image](https://user-images.githubusercontent.com/214067/66466506-1c6c8480-ea83-11e9-9732-81c46093d244.png)

On voit que sur une seule lettre (peut-être 2 en mobile, ça dépendra des lettres en plus) la marge n'est pas suffisante pour forcer le retour à la ligne. Néanmoins j'ai préféré garder ces 30% en me disant que d'une part des titres d'une ou deux lettres ne seraient guère fréquents ;) et d'autre part qu'en augmentant la marge on prend le risque si jamais une date devient plus longue (par exemple "novembre" ou "2020" prennent quelques pixels de plus) ça peut être vraiment laid. En effet il ne faut pas trop s'énerver sur ladite marge, sinon la date n'a plus assez de place pour s'afficher sur une ligne :

![image](https://user-images.githubusercontent.com/214067/66466750-82590c00-ea83-11e9-8674-b43b4514ebd1.png)
