### ISSUE TITLE
Ressource type image

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#20]
* [x] Création
* [x] Upload de multiples formats d'images
* [x] Mise à jour
* [x] Suppression

**Comment by naholyr** [comment]
TODO mise à jour des fichiers uploadés (possible ?)

**Comment by TomBor** [comment]
Sur le support de multiples formats, la ressource image diffère de la carte. Là où la carte (#53) gère trois tailles et trois résolutions, la ressource image ne gère que trois résolution ( ` ` (=@1x), `@2x`, `@3x`).

Donc dans le nom de fichier, il n'est pas question de `small`, `medium` ou `large`

**Comment by naholyr** [comment]
Comme je n'ai finalement pas eu le temps de faire le type "carte", ça
signifie qu'on peut faire comme ça :
- "carte" serait l'actuel "image" (1 à 9 fichiers)
- "image" serait l'actuel "image" sans la gestion des tailles (1 à 3
fichiers)

C'est bien ça ?

**Comment by TomBor** [comment]
Exactement

**Comment by naholyr** [comment]
Reste à faire : transcription (déplacé dans #78)
