### ISSUE TITLE
reconnaissance des définitions

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#200]
Depuis la mise à jour des dépendances, la reconnaissance des définitions dans les articles ne fonctionnent plus.

**Comment by naholyr** [comment]
non reproduit ensemble pour le moment, à retester avec les fichiers d'exemple

**Comment by naholyr** [comment]
J'ai ajouté le lexique puis les 3 docs (ceux fournis par @TomBor) et je n'ai pas de définitions manquantes

![image](https://user-images.githubusercontent.com/214067/66483889-42efe700-eaa6-11e9-97a3-3c14bf925c84.png)

En revanche dans les documents je ne vois aucun élément surligné dans la page. Je vérifie le parsing…

**Comment by naholyr** [comment]
Oh il était fourbe celui-là :D sur les documents non reconnus, la couleur était passée de `#ff0000` à… `#FF0000` ! Ce qui est évidemment tout à fait valide, j'ai donc corrigé le parsing.
![image](https://user-images.githubusercontent.com/214067/66484911-28b70880-eaa8-11e9-9b26-ef9bc0d230fd.png)

**Comment by TomBor** [comment]
👀 Bien vu !
