### ISSUE TITLE
FO : lexique

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#201]
- l'affichage des définitions des lexique en accordéon ne fonctionne plus
- les liens internes au lexique ne fonctionnent plus (voir aussi)
- il faut ajouter un bouton pour remonter en haut de la page comme pour les articles

**Comment by naholyr** [comment]
A priori c'est tout le clic qui est bloqué

Ajouter le même bouton de remontée que les articles
