### ISSUE TITLE
gestion du multilingue

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#202]
- il faut ajouter un bouton FR/EN sur la page d'accueil en haut à droite de l'écran à la place de la loupe ; quand on est sur le site en français, c'est le bouton EN qui s'affiche ; quand on est sur la version anglaise, c'est le bouton FR.
- il faut supprimer le menu langue dans le menu burger et le remplacer par l'option de recherche
- il faut désactiver les boutons EN/FR des résumés sur la page article et supprimer le lien vers la version française ou anglaise (à côté du titre), lequel est remplacé par le bouton EN/FR disponible en haut à droite de la page
- il faut supprimer dans les pages des ressources (= recherche) la mention de la langue qui suit le titre de la ressource  ; ex : Poverty and Environmental Degradation **(english)**
- dans le BO,  menu "rubriques", il faut ajouter un filtre de sélection sur la langue des ressources affichées dans le tableau (possibilité de sélectionner une ou l'autre, si les deux alors il pourrait être intéressant d'ajouter une couleur warning quand les deux valeurs sont différentes)

**Comment by naholyr** [comment]
Reste à faire :

- Responsive (cacher la loupe pour le breakpoint mobile)
- Filtre dans la section "topics" du BO

**Comment by TomBor** [comment]
Bonne idée. Une préférence pour la version courte qui ne posera pas de problème de taille sur mobile.

**Comment by naholyr** [comment]
En effet, j'obtiens ça en jouant sur le padding en mobile :

![image](https://user-images.githubusercontent.com/214067/66498213-016b3600-eabe-11e9-8234-e48a6428271e.png)

Du coup on part sur cette version ? Et dans le menu gauche je laisse la recherche ?

**Comment by naholyr** [comment]
Avec un titre long ça fait moins joli :
![image](https://user-images.githubusercontent.com/214067/66498695-c3224680-eabe-11e9-93b8-8dc0f30d0ed5.png)

En modifiant la position du titre j'obtiens quelque-chose de correct dans différentes résolutions :
![image](https://user-images.githubusercontent.com/214067/66498899-244a1a00-eabf-11e9-91ab-acb4dd76850a.png)
![image](https://user-images.githubusercontent.com/214067/66498948-32983600-eabf-11e9-806c-8e438e4eb81a.png)
![image](https://user-images.githubusercontent.com/214067/66498987-3e83f800-eabf-11e9-9174-88e9221ad9b3.png)
![image](https://user-images.githubusercontent.com/214067/66499100-725f1d80-eabf-11e9-91db-735f9e1ac185.png)
![image](https://user-images.githubusercontent.com/214067/66499166-928edc80-eabf-11e9-8e97-073825ca9b48.png)

Sur très petite résolution ça fait encore assez serré :
![image](https://user-images.githubusercontent.com/214067/66499033-5491b880-eabf-11e9-9859-4d060b8e4039.png)
![image](https://user-images.githubusercontent.com/214067/66499141-8440c080-eabf-11e9-861d-036d709e6515.png)

Soit on fait avec soit on réduit un peu la largeur du titre/logo dans cette situation ?

**Comment by TomBor** [comment]
Du côté du menu latéral, on laisse le champs de recherche tous le temps (mobile et desktop).
Pour le sélecteur dans la topbar je propose que pour la version mobile on supprime le picto de recherche. Ça règle les problèmes de taille avec le logo ou les titres d'articles.

**Comment by naholyr** [comment]
Ajout du filtre langue dans le BO → that's all folks :)
