### ISSUE TITLE
BO : Formulaire cassé après sélection d'un doc

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#203]
Après sélection d'un doc à uploader, le formulaire devient quasiment vide:

![image](https://user-images.githubusercontent.com/214067/66464424-3f953500-ea7f-11e9-9aea-82fa7dabf0f5.png)

**Comment by naholyr** [comment]
Note : c'est le champ "type" qui se vide et provoque la disparition du formulaire

**Comment by naholyr** [comment]
C'était causé par l'ajout récent de `href="#!docpicker"` pour faire sauter un warning d'accessibilité, mais mal intégré

**Comment by TomBor** [comment]
Maintenant à l'import de n'importe quel article j'ai cette nouvelle erreur bloquante : `exports.getText is not a function`
<img width="396" alt="Capture d’écran 2019-10-09 à 17 21 36" src="https://user-images.githubusercontent.com/8322713/66495287-50fb3300-eab9-11e9-9b5a-32794b11011d.png">

**Comment by naholyr** [comment]
Je n'ai pas mon PC à disposition pour vous dépanner, néanmoins je pense que la coquille était dans mon dernier commit de "nettoyage" où je n'ai pas du correctement tester l'import ensuite.

Dans ce fichier, lignes 20 et 21, il devrait suffire de supprimer "exports." dans les deux lignes (exports.getText → getText, et exports.parseMarkup → parseMarkup).
@TomBor si ce n'est effectivement que ça tu pourras débloquer directement 👍

**Comment by TomBor** [comment]
@naholyr Bien vu ! C'était effectivement ça.
