### ISSUE TITLE
FO - bug lien source dans ressource page

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#206]
Dans la page d'une ressource carte en français, si le champs source contient un lien marqué comme lien dans le backoffice, le texte du lien saute à l'affichage et le lien se propage sur tout les éléments suivants (commentaires, téléchargement).
ex : https://espace-mondial-atlas.sciencespo.fr/fr/rubrique-contrastes-et-inegalites/carte-1C04-acces-a-la-sante-2014.html

Peut être un problème de l'éditeur du backoffice qui générerait une balise <a> avec une mauvaise syntaxe ?

**Comment by TomBor** [comment]
- [ ] plus généralement le champs source d'une carte n'est plus affiché dans une page article

**Comment by TomBor** [comment]
@naholyr quand tu as restructuré le code du fichier EmbeddedResource.js pour l'accessiblité tu as fait sauté une spécificité du cas des cartes dans le switch qui affichait le champs source plutôt que copyright.
Actuellement les cas d'une image et d'une carte ont le même comportement : https://github.com/AtelierCartographie/eatlas/blob/master/client/src/components/preview/EmbeddedResource.js#L89
Comme fix temporaire à mon niveau, j'ai forcé l'affichage de la source.
Pour revenir comme avant, il faut : 
-   si la ressource est une image, la figcaption affiche le champs copyright
-   si la ressource est une carte, la figcaption affiche le champs source

**Comment by naholyr** [comment]
A priori le problème est lié à l'insertion automatique du "title" dans les liens WYSIWYG. Je vais revoir mon algo de transformation…

**Comment by naholyr** [comment]
Ça devrait être bon :)
