### ISSUE TITLE
FO - i18n dans toutes les réutilisation de seeAlso

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#209]
Dans la version EN, le nom de la rubrique est toujours en anglais dans les "voir aussi" d'un article ou lien article suivant / précédent.
ex : https://espace-mondial-atlas.sciencespo.fr/en/topic-contrasts-and-inequalities/article-1A01-EN-rich-and-poor.html

**Comment by delphinelrcl** [comment]
Tu veux dire toujours en français ?

**Comment by TomBor** [comment]
oui !
