### ISSUE TITLE
BO : règles dépendance entre article et focus à inverser

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#210]
Pour certains articles, une fois publié, et donc ses dépendances aussi (cartes, photos). Il est impossible de le dépublier ou de le supprimer, idem pour ses dépendances.

Est-ce que cela vient des règles de dépendances établies ?

**Comment by naholyr** [comment]
Après réflexion, je ne suis pas sûr de ce qui est le mieux fonctionnellement, mais j'ai l'impression qu'il ne serait pas illogique qu'il n'y ait pas de dépendance entre article et focus. En effet :

- Un focus n'est listé dans l'interface que si son article lié existe, donc si l'article n'est pas publié, le focus n'a aucune raison de l'être. C'est le sens actuel de la dépendance, mais si elle est fonctionnellement logique, elle est perturbante au niveau du backend.
- En revanche dans l'autre dépendance, c'est moins perturbant mais ce n'est pas logique car un article n'a pas besoin que son focus soit publié pour être lui-même publié, c'est une ressource "à côté", pas une ressource qui le compose.

Du coup comme aucune de ces deux relations n'est vraiment facile à gérer pour le contributeur, peut-être que le plus simple est de n'en avoir aucune ;)

Je vais partir sur cette hypothèse et on en reparlera plus tard si ça ne convient pas.

**Comment by naholyr** [comment]
J'ai largement assoupli la règle, je vous laisserai vérifier si cette souplesse est gênante pour le fonctionnement, ou si au contraire elle permet d'obtenir le confort souhaité.
