### ISSUE TITLE
Méta-données : liens externes

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#32]
- Seulement pour les articles & focus
- Rendu : liste de liens en fin d'article

**Comment by TomBor** [comment]
Les liens externes apparaissent à quatre endroits : 

- dans le corps de l'article
- dans les références
- dans les footnotes
- dans les sources des cartes (mais ici réutilisation de la méta sous-titre)

Pour le moment le parsage des docx ne reconnait pas les liens

**Comment by naholyr** [comment]
Géré dans la tâche globale de génération du HTML
