### ISSUE TITLE
Identifiant optionnel

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#34]
Actuellement, l'id est obligatoire. Le tableau des méta-données indique qu'il est optionnel, à voir ensemble pour la mise en place réelle de ce caractère optionnel.

![](https://lh3.googleusercontent.com/-v_fpdTbqiBI/WmCB7WqcevI/AAAAAAAAm7Q/VyR5BUSTvQgL1hfr2h4qxXJxNRsX3IPhACL0BGAYYCw/h566/2018-01-18.png)

**Comment by TomBor** [comment]
L'ID est bien obligatoire, on l'a prévu pour toutes les ressources sauf les définitions du lexique.
À voir si c'est un problème de votre côté que les définitions n'aient pas d'ID.

On renvoie bientôt un tableau des métadonnées à jour.
