### ISSUE TITLE
Ressources : filtrage de la liste

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#37]
Pouvoir filtrer par :

- [x] Type
- [x] Statut
- [x] Rubrique
- [ ] Recherche textuelle

Pouvoir trier par :

- [x] Tout sauf preview

**Comment by TomBor** [comment]
**LES FILTRES**

+   par type
+   par statut
+   par partie (rubrique renommé)

Prévoir un compteur (ex: Vidéos (2) )

**LE TRI**
Sur toutes les colonnes des résultats

**Un champs de recherche**
Sur toutes les métadonnées

**Comment by TomBor** [comment]
Renforcer les filtres sélectionnées pour mieux les distinguer => ajout d'un background ?

**Comment by naholyr** [comment]
Reste à faire : le champ de recherche full text

**Comment by naholyr** [comment]
Note : comme tous les autres filtres, c'est côté client uniquement
