### ISSUE TITLE
Idée workflow : parsing d'un article AVANT sauvegarde

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#41]
Idée sous-jacente : les métas d'un article sont contenus dans le corps du document word, aujourd'hui on doit donc faire une double saisie (les méta dans le corps du docx ne sont pas enregistrées dans les champs correspondant). Pour le sprint 3, deux approches :

- Rendre les champs optionnels côté formulaire de création d'article, remplir les données après parsing côté serveur, puis retrouver ses valeurs dans la fiche d'édition ensuite
  - Problème : des champs en apparence optionnels sont en réalité obligatoires
- Effectuer le parsing du docx par le serveur sur le `onPick` et remplir les champs une fois la réponse du serveur obtenu
  - Ces champs doivent-ils être carrément en read-only ou sont-ils rééditables ?

**Comment by Delapouite** [comment]
https://github.com/AtelierCartographie/eatlas/commit/bcf6b67a94a89808698f00aed39639730f1ef489
