### ISSUE TITLE
Article : ajouter une méta pour la photo d'entête

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#45]
Étape 1 : définir la méta

**Comment by TomBor** [comment]
Selon la même notation que les autres méta d'un article, on propose ça :
`{Image header}: “xPxx”`

**Comment by Delapouite** [comment]
Meta parsée : https://github.com/AtelierCartographie/eatlas/blob/master/server/lib/doc-parser.js#L33
