### ISSUE TITLE
Type : Définition

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#46]
Discussion sur la mise en place du type "définition", la grande question étant comment on règle les variantes de mots

* Manuellement dans l'article (id de la définition entre crocher à côté du mot en rouge)
* Manuellement dans le lexique (ajout de toutes les variantes dans le lexique)
* Automatiquement avec analyse de texte (mais quid du cas d'homonymes avec définitions différentes, ou de mots qui n'ont rien à voir orthographiquement mais ont la même définition ?)

**Comment by TomBor** [comment]
On partirait sur le seconde solution, celle des alias proposée par Bruno.

On aurait alors comme méta :   

+   Nom
+   Alias (plusieurs possibles)
+   Lien interne (renvoie vers une autre définition)
+   Fait partie de (automatique d'après l'utilisation dans les articles ou focus)

**Comment by delphinelrcl** [comment]
Les définitions seront gérées à partir d'un fichier csv qui sera importé manuellement ; chaque nouvel import écrasera les données préalablement importées : il faudra donc prévoir un message d'avertissement.. 

Les alias seront listés dans le fichier csv et séparés par une virgule.

**Comment by TomBor** [comment]
Proposition de notation des alias: `{alias}: [“alias 1”, “alias 2”, “alias 3”]`

Et aperçu dans le fichier lexique : 
![capture d ecran 2018-02-16 a 17 00 36](https://user-images.githubusercontent.com/8322713/36316587-fcc5db8e-133a-11e8-9dd7-198b82abde5d.png)

**Comment by naholyr** [comment]
Afin de simplifier la saisie, et comme ce n'était pas plus compliqué (au contraire, plus simple à parser et moins de risque d'erreur avec les joies des guillemets), j'ai mis en place deux syntaxes qui peuvent être utilisées à votre bon vouloir :

* `{alias}: ["alias 1", "alias 2"]`
  * le `:` est facultatif
  * les guillemets peuvent être `"` (informatique), `“`/`”` (anglais) ou `«`/`»` (français), car lors de la frappe dans Word ou Google Docs, ce petit malin a tendance à les transformer (on le voit d'ailleurs sur le screenshot)
* Craignant les éventuels problèmes qu'il y aurait avec ce format, j'ai donc ajouté la possibilité de déclarer les alias comme ceci :

```
{alias} alias 1
{alias} alias 2
```

Un alias par ligne, `:` facultatif, pas de guillemet

**Comment by TomBor** [comment]
Sage décision ! Merci beaucoup.

**Comment by naholyr** [comment]
Bug observé : le parsing est limité à une seule ligne, ainsi on ne peut pas définir plusieurs alias avec la syntaxe simplifiée `{alias} mot(s)`

**Comment by naholyr** [comment]
Pour info, voici trois méthodes de saisie dont on attend qu'elles donnent le même résultat :
![image](https://user-images.githubusercontent.com/214067/45222765-aad96a00-b2b5-11e8-81bc-a65c5dc12782.png)

En cours…

**Comment by naholyr** [comment]
Le parsing modifié, ça devrait être bon

**Comment by TomBor** [comment]
Testé et confirmé.
Merci !
