### ISSUE TITLE
Type : Focus

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#47]
- Rendu différent de celui d'un article
  - Pas de photo de couverture
- Relation focus →n..1→ articles

**Comment by TomBor** [comment]
Voir charte graphique (pdf) p. 15 et 16.
![capture d ecran 2018-02-16 a 16 46 36](https://user-images.githubusercontent.com/8322713/36315886-1aa9c202-1339-11e8-81a6-f168e2a77eaa.png)
