### ISSUE TITLE
Type : Vidéo

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#48]
- URL Vimeo
- Quid de la transcription

**Comment by delphinelrcl** [comment]
exemples de videos hébergées sur le Viméo ScPo 
https://vimeo.com/sciencespoaudiovisuel

**Comment by Delapouite** [comment]
Les ressources de type vidéo peuvent désormais etre ajoutées.
Pour qu'elles soit considérées valides, il faut renseigner une URL vimeo dans le champ `media url`.
A voir plus tard pour étendre vers d'autres providers (youtube…)

**Comment by naholyr** [comment]
Reste à faire : transcription (déplacé dans #78)
