### ISSUE TITLE
Type : Son

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#49]
- Upload de fichier son
- Quid de la transcription ?

**Comment by Delapouite** [comment]
L'utilisateur peut maintenant picker des mp3s depuis Gdrive

**Comment by delphinelrcl** [comment]
Oui, prévoir de rajouter un champ d'upload d'un fichier texte contenant la transcription pour les vidéos et les sons. A voir quel usage en sera fait : soit mettre ce fichier en simple téléchargement, soit ajouter une accordéon qui affiche le texte de la transcription sous la vidéo ou le son.

**Comment by naholyr** [comment]
Reste à faire : transcription (déplacé dans #78)
