### ISSUE TITLE
Type : cartes

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#53]
Finalement ne prend pas en compte le format svg mais des images. Soit le même fonctionnement que la ressource "photos" avec plusieurs tailles et résolutions.

**Comment by TomBor** [comment]
Prévoir une nouvelle métadonnée "data" qui supporterai des fichiers textes (par exemple csv)

**Comment by TomBor** [comment]
Pour résumer :

- [ ] format svg abandonné au profit d'une copie du type image
- [ ] nouvelle métadonnée `data` qui supporterai l'import d'un fichier texte (type csv)
- [ ] nouvelle métadonnée `source` qui supporterai les liens (en markdown ? html ?)
- [ ] import multiple automatique via le nom des fichiers de type : [prefixe ID]-nom-du-doc-[suffixe taille][suffixe resolution].jpg (ex: `xCxx-nom-doc-small@2x.jpg`)   Taille = `small`, `medium`, `large` et Résolution = ` ` (=@1x), `@2x`, `@3x`
- [ ] frontend : prévoir un système à définir pour passer manuellement d'une taille à une autre. But montrer au lecteur qu'il existe plusieurs version et permettre son accès indépendamment de l'affichage automatique selon le support
- [ ] la taille du format **small** (p. 6 charte graphique) passe de 450 à **520px**

**Comment by naholyr** [comment]
Reste à faire : transcription (déplacé dans #78)

Je pense que dans un premier temps comme on n'aura pas le temps d'implémenter tous les détails des champs "data", "télécharger", etc… ce champ de "description enrichie" pourrait faire le job. Il devrait sûrement être nommé différemment du coup.
