### ISSUE TITLE
Charte graphique (page article)

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#61]
Une issue générale sur la partie front pour souligner les différences entre le prototype d'une page article que j'ai été en mesure de réaliser et ce que j'ai ensuite défini dans la charte graphique.

Notamment les points suivants (+ référence à la page du pdf de la charte) :   

- **Navbar** (p. 1) deux versions (blanche + bg transparent et noir + bg blanc) et deux états d'abord static puis fixed top
- **Placement du titre** (p. 3) trois positions aux choix à définir dans le backoffice + voir comment forcer le multi-lignes (jusqu'à 3)
- **Résumé** (p. 4) ajout de deux boutons de langue
- **Commentaire** (p. 8) graphiquement différent (texte partiellement affiché)
- **Définition** (p. 9) texte partiellement affiché si trop long + renvoi via un texte/bouton vers la définition complète
- **Footnotes et liens** (p. 10) pas de changement d'état, les footnotes sont aussi cliquables car déjà implémenté (tant mieux !) + pas de bleu
- **Footer > Continuer dans l'Atlas** (p.12) graphiquement différent
- **nav préc. suiv.** (p. 13) flèches flottantes seulement si écran large et apparaît après l’image d’en-tête d’article et disparait avant le footer d’article + ajout entre fin article et footer de zone de navigation précédent/suivant

**Comment by Delapouite** [comment]
Eclatage en sous issues:

- Navbar: il reste des ajustement de position à faire, le basculement de couleur c'est bon.
- Placement de titre: https://github.com/AtelierCartographie/eatlas/issues/82
- Résumé: ok
- Commentaire: https://github.com/AtelierCartographie/eatlas/issues/94
- Definition: https://github.com/AtelierCartographie/eatlas/issues/92
- Footnotes: encore un peu d'ajustement sur les couleur taille
- Continuer dans l'Atlas: ok
- Nav prec/suiv: https://github.com/AtelierCartographie/eatlas/issues/90
