### ISSUE TITLE
BO - page rubriques : ajouter une colonne pour chaque type de ressource

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#63]
Il faut ajouter dans le tableau une colonne pour chaque type de ressource (sauf définition), sur le même principe que pour le type article.

**Comment by delphinelrcl** [comment]
La colonne icône est à supprimer car finalement nous n'utiliserons pas d'icône...

**Comment by naholyr** [comment]
OK pour la suppression de l'icône, par contre pour la colonne à rajouter je n'ai pas compris ce qu'elle devait contenir ?

**Comment by annelhote** [comment]
Pareil, j'affecte à @delphinelrcl et @TomBor.

**Comment by TomBor** [comment]
La colonne article fait un compte du nombre d'article de la rubrique.
Il faudrait ajouter avec le même système de compte les colonnes suivantes :   

- Focus
- Carte
- Image
- Vidéo
- Son
