### ISSUE TITLE
BO - page ressources  : affichage du tableau de bord

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#65]
- [x] Il faut revoir l'ordre d'affichage des colonnes du tableau de bord, avec gauche à droite : statut, type, prévisualisation, identifiant, titre, auteur, date
- [x] La colonne auteur n'indique pas l'auteur de la ressource mais le déposant : il faut donc ajouter une nouvelle colonne "déposant". Le nom de l'auteur et du déposant doit s'afficher sous la forme prenom.nom
- [x] Il faut également prévoir une colonne plus large pour le titre, en rétrécissant par ex la colonne auteur ou identifiant. 
- [x] Il faut remplacer "crée le" par date de création et que la date s'affiche sous la forme JJ/MM/AAAA.
- [x] Pour la colonne prévisualisation, il faut pour les articles, ajouter une icone (par ex un panneau danger) pour indiquer si des ressources liées sont manquantes. 
- [x] Il faudrait ajouter entre ( ) le nombre de ressources pour chaque filtre (statut et rubrique), sur le même principe que pour les types de ressources, en précisant 0 quand le résultat est nul.

Est-il possible de prévoir une personnaliser des colonnes à afficher ? 

> edit by @naholyr : check-list

**Comment by delphinelrcl** [comment]
Il faudrait ajouter entre (  ) le nombre de ressources pour chaque critères de tri (statut et rubrique), sur le même principe que pour les types de ressources, en précisant 0 quand le résultat est nul.

**Comment by naholyr** [comment]
> Est-il possible de prévoir une personnaliser des colonnes à afficher ?

Il y a un système de configuration du front par variable d'environnement, c'est donc faisable, je profite du déplacement des colonnes pour rendre ça modifiable

**Comment by naholyr** [comment]
> La colonne auteur n'indique pas l'auteur de la ressource mais le déposant : il faut donc ajouter une nouvelle colonne "déposant". Le nom de l'auteur et du déposant doit s'afficher sous la forme prenom.nom

Ce n'est pas forcément une information qu'on a :

- L'auteur est une méta-donnée sémantique dans l'article, dans les exemples qu'on a c'est "Prénom Nom" mais ça peut être de n'importe quelle forme, et a priori pas forcément un utilisateur enregistré du back-office, si ?
- Le déposant est une donnée technique gérée par le serveur, donc on stocke l'identifiant (l'email, seule ressource fiable pour pointer un utilisateur), je peux utiliser le "Nom" de l'utilisateur au lieu de son email, mais si l'utilisateur est supprimé il ne restera que l'email

**Comment by TomBor** [comment]
Ca ira très bien comme ça.

**Comment by naholyr** [comment]
Résultat actuel :

![image](https://user-images.githubusercontent.com/214067/36476114-30c70622-16fd-11e8-8fb4-04566ca2142f.png)
