### ISSUE TITLE
BO - modifier une ressource de type article

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#66]
Il faudrait traduire les libellés des métadonnées et agrandir la taille du bloc "résumé" pour l'afficher sur plusieurs lignes. Il faut également revoir la taille des blocs "titre de paragraphe" et les aligner sur la taille des blocs de texte. 
Enfin, il faut ajouter un bouton "valider" pour enregistrer les modifications.

**Comment by naholyr** [comment]
Attention : les champs "paragraph", "header", etc… sont là pour vérification du parsing en fait. Il n'est pas possible d'en modifier le contenu (il faut passer par le ré-upload du document).

Je vais les transformer en simple `<span>` pour l'indiquer plus clairement, faire les traductions et également rendre cette partie escamotable afin de gagner de la place pour un accès plus simple au bouton de sauvegarde.
