### ISSUE TITLE
BO - ajouter une ressource de type article

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#67]
Il faut préciser les métadonnées obligatoires (cf le tableau). 

Quand on clique sur le bouton "sauver" il faut arriver sur la home page  des ressources (tableau de bord) avec par ordre d'affichage la dernière ressource créée. 
Le bouton "sauver" doit être remplacer par un bouton "valider" afin d'harmoniser les boutons de validation/enregistrement. 

### édition par @naholyr : check-list

- [x] Auteur de l'article/focus = méta-donnée (déjà stockée dans les nodes)
- [x] Auteur d'une autre ressource = champ texte libre optionnel
- [x] Déposant = utilisateur qui poste la ressource (lecture seule) (à définir : mis à jour ou garde sa valeur initiale)
- [x] Libellé du bouton de sauvegarde = "valider"
- [x] Redirection sur la liste des ressources après création/modification d'une ressource
- [x] Sur la redirection, la liste doit être triée par date de modification (plus récent en premier)

**Comment by annelhote** [comment]
<img width="884" alt="screen shot 2018-02-19 at 12 13 06" src="https://user-images.githubusercontent.com/1478919/36375126-617c42e0-156e-11e8-878f-886efb3c38c6.png">

**Comment by naholyr** [comment]
Il y a plus de méta que dans le cahier des charges originales, quelques questions sur ce nouveau tableau du coup :

- Il y a "sous-titre" et "source (ex sous-titre)", ce sont bien deux champs différents (donc ajout du champ "source") ?
- quel est le rôle du champ "data" ?
- quel est le rôle du champ "alias" ?
- quel est le rôle du champ "déposant" ?
- quel est le rôle du champ "transcription" ?

**Comment by annelhote** [comment]
Vu que tu as vu. J'assigne Delphine et Thomas. A voir qui pourra répondre à cette question.

**Comment by TomBor** [comment]
- `Auteur` est bien celui qui à crée la ressource (écrit le texte, réalisé la carte...)
- `Déposant` est l'utilisateur qui a importé la ressource dans le backoffice

**Comment by naholyr** [comment]
Question sur le déposant : est-ce le créateur original de la ressource, ou le dernier qui a effectué une modification ?

**Comment by TomBor** [comment]
Plutôt qui à effectué la dernière modification
