### ISSUE TITLE
BO - ajouter une ressource de type image (carte ou photo)

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#68]
Plutôt que de télécharger manuellement les 9 images, il faudrait pouvoir n'en choisir qu'une (obligatoire) et par défaut importer automatiquement les autres tailles d'image dont l'identifiant est le même. 
Serait-il possible de présenter sous la forme d'une galerie les différentes images téléchargées ? 

Il faut remplacer le bouton "sauver" par "valider". Un clic sur ce bouton doit afficher la page d'accueil des ressources (tableau de bord).

**Comment by naholyr** [comment]
J'ai pu mettre en place la preview dans toutes les situations (fraichement sélectionné, ou fichier déjà sauvegardé),  ça donne ça :

![image](https://user-images.githubusercontent.com/214067/36494609-c8fb0332-1732-11e8-98be-839ea04878f0.png)
