### ISSUE TITLE
BO - Création d'un nouvel article - Changement de fichier lié

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#69]
1. Aller sur le formulaire pour la création d'un nouvel article
2. Importer un fichier docx d'un article du drive
3. Suite à une erreur dans le choix du fichier, je charge un autre fichier docx d'un article du drive
4. Lors de la sauvegarde de ce nouvel article, message d'erreur

**Comment by annelhote** [comment]
<img width="1368" alt="screen shot 2018-02-19 at 11 30 23" src="https://user-images.githubusercontent.com/1478919/36373594-e12dbf88-1568-11e8-9715-79b16c079602.png">
