### ISSUE TITLE
BO - Article - Prévisualisation

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#70]
Si la meta {Image header} n'est pas settée, l'image par défaut est celle des casques bleus de l'ONU.
Nous souhaiterions qu'aucune image n'apparaisse dans ce cas.

**Comment by naholyr** [comment]
Lors de la démo il n'y avait aucune image, ça doit donc être une modif très récente

**Comment by annelhote** [comment]
Où une modif' non commitée ? Je ne trouve plus le bug mais dans la démo, on avait également vu un lien vers une preview partageable de l'article que l'on ne voit plus maintenant. A déclarer dans un autre bug ?

**Comment by naholyr** [comment]
J'en ai profiter pour mettre en place le lien **réel** entre article et ressources.

J'ai également ajouté une fonctionnalité dans la preview à ce sujet : ajouter `?published=true` à l'URL de preview va exclure de l'affichage toutes les ressources qui n'ont pas le statut "published", c'est en quelque sorte une vue plus "réaliste" de l'article en fonction du statut actuel des ressources. Par défaut on continue d'ignorer le statut des ressources liées pour le moment.
