### ISSUE TITLE
BO - Lexicon - Upload

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#72]
Lors de l'upload d'un nouveau lexique, message d'erreur en raison d'absence de resourceId. Or cette fonctionnalité est obsolète, il n'y a plus de resourceId lié aux définitions.

**Comment by annelhote** [comment]
<img width="1792" alt="screen shot 2018-02-19 at 11 51 40" src="https://user-images.githubusercontent.com/1478919/36374392-7c617c68-156b-11e8-8826-437d5815de58.png">

**Comment by naholyr** [comment]
En effet la suppression de cette info n'a pas été implémenté de suite
