### ISSUE TITLE
BO - Tableau de bord - Pagination

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#75]
Quid de la pagination si beaucoup de ressources à charger ? Ou bien pagination, ou bien lazy loading. Choix technique à faire.
Choix préféré celui de la pagination si on peut choisir le nombre de résultats par page.

**Comment by naholyr** [comment]
Pour le moment on a fait le choix (permettant d'aller vite et de réduire les temps de chargement) de charger l'intégralité des ressources avec leur méta-données au démarrage. La pagination serait donc le plus simple à mettre en place et en affichage instantané (le problème n'est pas la quantité de données chargées, mais plutôt la quantité de données *affichées* le lazy-loading ne répondra pas à cette problématique).

Je pense que ce choix de conception est tenable à long terme (même avec plusieurs centaines d'articles et plusieurs milliers de ressources, les méta-données restent légères) et pourra être optimisé pour ne récupérer que ce qui est nécessaire à l'affichage de la liste (par exemple les nodes, définitions, description, sous-titre, etc… n'ont pas besoin d'être chargés en mémoire avant d'arriver en mode édition).

Bref : pagination :)

**Comment by annelhote** [comment]
Lié à #24 ?

**Comment by naholyr** [comment]
Oui, mais ça reste deux sujets différents (actuellement on peut faire une
pagination front, permettant de réduire la charge de la page par exemple,
sans pour autant faire une pagination des requêtes), donc pas de souci
particulier
