### ISSUE TITLE
Faire fonctionner CORS en production

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#76]
Comportement actuel :

- si on active CORS, la communication intra-domaine échoue sous Chrome
- si on le désactive, en fait on passe en mode "allow no origin" ce qui ouvre l'API

On souhaite corriger ces deux points

**Comment by naholyr** [comment]
Le problème : Chrome n'ajoute pas le header "Origin" quand il effectue une requête vers un serveur de même host que la page en cours

**Comment by naholyr** [comment]
Tests effectués :

- remplacer l'utilisation de `fetch()` par `XMLHttpRequest` (conservé, ça permettra d'éviter un polyfill)
  - sans effet
- modifier les headers dans nginx
  - suppression d'une ou plusieurs instructions 'add_header' sans effet
  - ajout de `add_header Referrer-Policy origin;` sans effet

Dans toutes les configurations testées, à partir du moment où la requête est faite sur le même domaine, Chrome n'inclut pas le header `Origin`, et la vérification devient impossible côté serveur. Je n'ai trouvé aucune info là-dessus, ça semble être un comportement normal.

Je pense qu'on peut conserver la configuration actuelle consistant à autoriser le "*no origin*", en effet :

- cela permettra de faire fonctionner Chrome
- les scripts JS tournant dans un navigateur essayant d'interroger notre API passeront le header Origin dans tous les cas (puisque domaine différent) et donc le middleware CORS les rejettera
  - il n'est pas possible de modifier côté JS le header "origin", donc on est sûr que ce type de situation sera géré correctement
- les situations qu'on ne peut pas protéger sont :
  - l'utilisateur utilise une extension navigateur pour modifier le header "origin"
  - l'utilisateur requête notre API avec un script fait maison
  - dans ces deux cas, qu'on accepte ou non le "*no origin*", il a de toute façon le contrôle sur le header et peut donc passer les barrières sans difficulté

J'en conclus que "allow no origin" ne représente pas un trou de sécurité, puisqu'on reste protégé des cas  où `origin` ≠ valeur autorisée.

**Comment by naholyr** [comment]
Note : peut-être devrait-on renommer l'option de configuration `DISABLE_CORS` en `CORS_ALLOW_NO_ORIGIN` plus spécifique et indiquant plus clairement la direction prise (ainsi que les impacts, ou plutôt leur absence :), sur la sécurité)

**Comment by jri-sp** [comment]
Je suis d'accord. J'avais mal compris le code et je pensais qu'il n'y avait aucune vérification avec "allow no origin", mais si... Donc ça me convient comme comportement.
La variable est modifiée (228acec1f38fa31b126f09bc889257aa1607b2dd) ! 
On peut fermer l'issue je pense...

**Comment by naholyr** [comment]
Nickel je n'attendais que ton retour pour ça, merci !
