### ISSUE TITLE
Regeneration site public

### ISSUE THREAD

**Issue by Delapouite** [AtelierCartographie/eatlas#77]
# modification…

## du **lexique**

- regénération de *tous* les articles et focus

## d'une **image/son/vidéo/carte**

- regenerer la page ressource (p. 18 et suivantes)

## d'un **focus** 

- regénération du focus et de tous les articles liés, ainsi que le topic auquel appartient le focus (bande jaune p. 17)

## d'un **article** 

- regénération de l'article et de son topic

**Comment by naholyr** [comment]
# Liste des pages et de leurs dépendances

Note : les URLs seront modifiables dans la configuration `json` du serveur, donc ce n'est pas figé dans le marbre. En revanche il sera déconseillé de les modifier une fois le site lancé.

## Toutes les pages

Toutes les pages incluent le menu "topic" (sous forme de top menu ou de menu burger, ou en footer), dépendant de :

- Liste des topics (id + titre → url)
- Liste des articles (id + titre → url)
- Toutes les pages doivent donc être régénérées en cas d'**ajout, suppression ou modification d'un article ou d'un focus**

Note : on pourrait mettre en place des règles plus fines comme limiter la régénération à la modification du titre seulement, mais on aura forcément des cas particulier et ces règles ne pourront être définies que plus tard.

## Pages globales

### Accueil

- `index.html`
  - Pas de règle de regénération particulière

### Moteur de recherche

- `recherche.html`
  - Pas de règle de regénération particulière
- Page dynamique générée côté client en JS (vanilla) et interrogeant l'API public `/search` (cf. #79)
- Les résultats et leur filtrage sont gérés côté client
- Le script va également parser (voire modifier si possible) la *query string* pour permettre des URLs réutilisables (cf. pages ressources)

### Pages "Ressources" (footer)

- `ressources-{label type}.html`
  - Pas de règle de regénération particulière
  - Pour avoir des URLs "friendly", on prévoira une correspondance entre le type réel (ex. `sound`) et le libellé dans l'URL (ex. `audio`)
- Pour simplifier le développement, on partirait sur une déclinaison du moteur de recherche (en ajoutant un `<script>` initialisant le moteur en fonction)
  - Le champ de recherche est caché, le type de chaque résultat est caché

### Pages "À propos"

- Qui sommes-nous `a-propos/qui-sommes-nous.html`
  - Pas de règle de regénération particulière
- Nous contacter `a-propos/contact.html`
  - Pas de règle de regénération particulière
- Mentions légales `a-propos/mentions-legales.html`
  - Pas de règle de regénération particulière
- Plan du site `a-propos/plan-du-site.html`
  - Régénéré à chaque **ajout, suppression ou modification d'une ressource quelconque**

### Pages de ressource

- Topic `rubrique-{slug titre}.html`
  - Dépend des articles & topics par le top-menu
  - Dépend aussi de la liste de ses focus
- Ressource `rubrique-{slug titre topic}/{label type}-{id}-{slug titre}.html`
  - Dépend des articles & topics par le top-menu
  - Pour les articles et les focus, regénérer en cas de modification de ses ressources liées (related articles, focus, définitions, image, son, vidéo, etc...)

**Comment by naholyr** [comment]
# Détail du déclenchement de la régénération

- Ajout/suppression/modification d'une rubrique : régénération de **toutes** les pages
- Ajout/suppression/modification d'un article : régénération de **toutes** les pages
- Ajout/suppression/modification d'un focus : régénération de la page du topic, de l'article lié, et de la page du focus
- Ajout/suppression/modification d'une photo : régénération de la page de l'article ou du focus lié, et de la page de la ressource
- Ajout/suppression/modification d'une carte : régénération de la page de l'article ou du focus lié, et de la page de la ressource
- Ajout/suppression/modification d'un son : régénération de la page de l'article ou du focus lié, et de la page de la ressource
- Ajout/suppression/modification d'une vidéo : régénération de la page de l'article ou du focus lié, et de la page de la ressource
- Remplacement du lexique : régénération de **toutes** les pages **articles et focus**

**Comment by naholyr** [comment]
Afin d'appliquer l'adage “Cool URLs don't change” je vais ajouter un champ "url" aux ressources et aux topics, qui n'est jamais modifié même si le titre ou le topic change.

À terme ce champ deviendra modifiable, et afin de gérer les versions et les modifications de titre, on pourra ajouter un champ "oldUrls" multivalué pour ajouter des redirections.

**Comment by naholyr** [comment]
Note pour le référencement : ne pas toucher aux pages dont le contenu n'est pas effectivement modifié, afin de ne pas changer la date de dernière modif pour rien.
