### ISSUE TITLE
Accessibilité : Transcription textuelle des contenus

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#78]
Concerne au moins les types `audio` et `video`, mais aussi a priori `image` et `map`

* [x] Ajouter sur les types concernés un nouveau champ texte optionel `transcription`
* [ ] Ce champ doit accepter la mise en forme HTML simple (gras, liste…)

**Comment by Delapouite** [comment]
Champ transcript ajouté dans https://github.com/AtelierCartographie/eatlas/commit/4c75ff0e5475e7a6c3e1d591fbad5cb42248a6eb

Le WYSIWYG sera traité plus globalement dans https://github.com/AtelierCartographie/eatlas/issues/124
