### ISSUE TITLE
Implémentation du moteur de recherche front

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#79]
## Côté backend

Création d'une nouvelle route `POST /search` dédiée à la recherche de ressources

### Entrée : JSON

* `query` (`string`) : la chaîne de recherche full text
* `count` (`number`) : le nombre d'items retournés par page
* `page?` (`number`) : le numéro de page demandé (par défaut 1)
* `topics?` (`number[]`) : les IDs des rubriques
* `keywords?` (`string[]`) : les mots-clés (cf. méta des articles)
* `date?` (couple `[string?, string?]`) : les dates min/max de publication
* `languages?` (`string[]`) : les langages supportés

### Sortie : JSON

* `total` (`number`) : le nombre total d'éléments retournés par la requête
* `page` (`number`) : la page actuelle
* `pages` (`number`) : le nombre total de pages
* `results` (`ResultItem[]`) : les items de résultats

#### Format `ResultItem`

À définir (conversion côté back d'une liste de `Resource` en liste de `ResultItem`) pour coller au mieux au besoin du front

## Côté frontend

* Appel Ajax à l'API (donc injection de l'URL du serveur d'API dans le JS du front)
* Génération des résultats

Challenge : JS old-school :fearful:

**Comment by naholyr** [comment]
# Description des problèmes inhérents à la recherche côté backend

Alors, description du "problème" elastic search… L'index à interroger est le suivant :

- index ES : [server/lib/es/types/resource.json](../blob/master/server/lib/es/types/resource.json)
- description Joi : [server/lib/schemas.js](../blob/master/server/lib/schemas.js#L122)

On doit pouvoir faire une recherche full text sur tous les champs des ressources, et filtrer par propriétés (a priori c'est facile, et je me demande si le filtrage ne sera pas fait côté client au final de toute façon) en paginant :

- topic (champ simple type keyword)
- keywords (champ nested "metas.list", multivalué type text, filtre à n'appliquer que pour les nested dont "metas.type" = "keywords")
- publishedAt (champ simple type date)
- language (champ simple type keyword)

La première difficulté est d'arriver à filtrer par keywords (n'appliquer un filtre que si une sous-partie des metas matche un critère…), je sais même pas si c'est permis. Le cas échéant je filtrerai manuellement mais ça imposera de faire la pagination en Node ce serait dommage. Mais c'est le plan B prévu si pas de solution immédiate.

La deuxième difficulté est qu'on doit mixer ça avec des "ressources virtuelles" qui ne sont pas des entrées dans l'index, mais des contenus dans ces entrées…

- lexique = un seul item (id = "LEXIC"), un résultat = un élément du champ "definitions" (champ multivalué type nested, avec les propriétés dt - le texte - dd - la définition - et aliases - les alias du titre)
- références = n items (type = "article" | "focus"), un résultat = un élément du champ "metas" d'un item, dont type = "references", et la valeur est "list"

En décrivant ces contraintes je me dis que c'est totalement impossible en l'état et qu'il faut réorganiser l'index. Donc en attendant de voir si on trouve une solution pour le faire en "full elastic" la première version sera :

- Elastic pour la requête full-text et filtra préliminaire (sans pagination)
- Filtrages complexes ou reformatage des résultats en Node
- Finalement pagination (avec Node forcément du coup)

**Comment by Delapouite** [comment]
Il reste encore un effort à faire au niveau du stylage qui reste pour le moment encore très brut.
La recherche est accessible depuis 3 champs:
- dans le menu en haut de chaque partie
- dans le menu latéral de chaque article / focus
- dans la page d'accueil

**Comment by Delapouite** [comment]
Gestion des keywords: https://github.com/AtelierCartographie/eatlas/commit/3188f12154ff0829f7472bf72ca96557422e3615

**Comment by naholyr** [comment]
* Ajout de l'url de recherche persistante
* Ajout du support de la recherche de lexique (il faut réimporter le fichier pour générer les entrées elastic)
* Ajout du support de la recherche de références (il faut re-valider chaque article pour générer les entrées elastic)

**Comment by Delapouite** [comment]
Branchement des définitions depuis le panneau gris qui s'affiche en bas des articles: https://github.com/AtelierCartographie/eatlas/commit/595a025365df3542ca3ccff81c5dae1f50ced7e8

**Comment by Delapouite** [comment]
Affichage des titres: https://github.com/AtelierCartographie/eatlas/commit/a9ab526549296cdafb6e2303b2d33bbbf99217fe
ex: 'Ressources > lexique'

**Comment by Delapouite** [comment]
Dans le cadre du lexique, les définitions ne sont pas renvoyées dans l'ordre alphabetique.

**Comment by delphinelrcl** [comment]
Les résultats d'une recherche doivent s'afficher selon les critères suivants et par ordre de préférence : 
1) définition si existante
2) titres d'une ressource (tout type confondu dont les articles et focus)
3) mots clés 
4) résumés et/ou commentaires

**Comment by naholyr** [comment]
complément : #148

**Comment by naholyr** [comment]
Pour la modification de l'ordre il faudra peut-être ajouter un champ numérique pour convertir le type en "ordre" et trier dessus, sauf si je trouve comment trier par un "enum" à voir après farfouillage dans la doc ;)

**Comment by naholyr** [comment]
En fait je n'ai pas compris ce que signifiait cette liste : initialement je pensais qu'on parlait de trier les résultats par type de ressource (définitions d'abord, autres ressources ensuite) mais "mots clés" et "résumés et/ou commentaires" ne sont pas des types de ressource, du coup je ne comprends pas l'algorithme de tri attendu ?

**Comment by delphinelrcl** [comment]
Oui c'est bien ca : on affiche d'abord les définitions puis sur les autres types de ressources on les affiche à selon les critères de pertinence (si le mot tape dans la requête apparait dans l'un des champs ci dessous ) suivant : 
- titre
- mot clé
- résumé  (article) ou commentaire (image)

**Comment by naholyr** [comment]
Après première analyse, je devrais pouvoir effectuer ce tri en utilisant :

- une fonction de tri custom pour trier par type
- du boost de score pour trier selon le champ matché

Les difficultés restant à valider :

- vérifier qu'une fonction de tri et le tri par score restent compatibles
  - si jamais ça ne fonctionne pas, le plan B consiste à ajouter un champ numérique dans elastic dédié au tri dont la valeur est calculée à partir du type de ressource
- trouver les bonnes valeurs de boost
- valider que le champ "résumé" pour les article et "commentaire" pour les images font bien référence au même champ dans elasticsearch (a priori oui, et au pire sauf quelques rares cas limite ça ne devrait pas gêner le résultat final)

**Comment by naholyr** [comment]
Configuration ajoutée, dites-moi (principalement @jri-sp) si c'est suffisamment parlant pour pouvoir le tweaker lors des tests :

```json
{
	"// searchSort": "Values to boost score for specific ordering",
	"searchSort": {
		"// boostType": "Boost score depending on doc's type",
		"boostType": {
			"single-definition": 100
		},
		"// boostSearchField": "Boost applied to standard searchFields listed above",
		"boostSearchField": {
			"title": 40,
			"description_fr": 3,
			"description_en": 3
		},
		"// boostSpecial": "Boost applied to specific search criteria: status, type, language, topic, or keywords",
		"boostSpecial": {
			"keywords": 10
		}
	}
}
```

**Comment by naholyr** [comment]
Blocage sur l'implémentation pour appliquer le boost aux requêtes multi-valuées: s'il y a un seul keyword aucun souci, si on en teste plusieurs je n'ai pas trouvé la syntaxe adaptée… En cours de recherche.

**Comment by naholyr** [comment]
OK l'approche devra donc être différente, mais permettra un résultat plus prédictible : chaque filtre va être wrappé dans une bloc "constant_score" de manière à fixer les score de chaque filtre. Les scores des composés "should" et "must" sont la somme des requêtes scores des sous-filtres, et on applique le multiplicateur final.

**Comment by naholyr** [comment]
J'ai fini avec un mélange de "boost" et de "constant_score", en effet le score constant donne des résultats plus prévisibles mais casse le tri par pertinence intégré d'Elastic Search, ce qui est dommage.

Vous avez à votre disposition cette configuration pour jouer sur le tri :

```json
{
  "// searchSort": "Rules to compute score for specific ordering",
	"searchSort": {
		"// boostType": "Boost score depending on doc's type",
		"boostType": {
			"single-definition": 1000
		},
		"// boostSearchField": "Boost applied to text searchFields listed above (not listed = 1)",
		"boostSearchField": {
			"title": 40,
			"description_fr": 10,
			"description_en": 10
		},
		"// scoreSpecial": "Score applied to specific search criteria: status, type, language, topic, or keyword (not listed = 0)",
		"scoreSpecial": {
			"keyword": 200
		}
  }
}
```

Il y a donc 3 grandes parties dans la recherche :

1. Les filtres excluant "simples" : langues, topics, types…
   - A priori ils n'ont pas à avoir d'impact dans l'ordre final, j'ai donc défini leur score à 0 (sauf modification dans la config ``searchSort.scoreSpecial``)
2. Les champs "full text" pour lesquels on souhaite un calcul de pertinence : tous ceux listés dans la config ``searchFields`` (titre, sous-titre, description fr & en, etc…)
   - On souhaite "booster" le score de certains de ces champs selon leur importance (ici titre et description) : c'est possible dans la config ``searchSort.boostSearchField`` (boost par défaut = 1 donc les champs non listé gardent quand-même un impact selon la pertinence)
   - Le score final de la recherche sur tous ces champs sera la somme de toutes les recherches
3. Les métas sont techniquement plus complexes (nested à deux niveau) à interroger
   - on trouve donc les mots-clés dans un bloc à part, dont le score est fixé par la config ``searchSort.scoreSpecial.keyword``
   - ce score est fixe et défini à l'avance

Le score final d'un document est la somme de tous ces scores cumulés. On applique alors finalement un multiplicateur (défini par la config ``searchSort.boostType``) en fonction du type de ressource, ici utilisé pour propulser les définitions en tête de résultat.

Le jeu consiste ensuite à définir les bonnes valeurs en configuration… Il faudra surtout faire du "try and see" pour peaufiner avec les vraies données et les vraies recherches.

### Comment j'ai choisi les valeurs par défaut

Par défaut il y a un boost de 1 sur les champs "full text" (dont titre et description_fr et description_en). Il y a 10 champs listés.

- Afin de s'assurer que la description ait plus d'importance que n'importe quel autre champs, je lui ai appliqué un **boost de 10 (= le nombre total de champs full text)**, ainsi si deux docs sortent, on est sûr que celui dont la description match sera devant l'autre même si *tous* ses autres champs matchent.
- Une fois ceci défini, j'ai une nouvelle somme des boosts qui est 28, j'ai donc appliqué un **boost de 40** au titre, en appliquant la même logique plus une bonne marge pour caler le score des mots-clés au milieu.
- Les mots-clés n'étant pas du full-text, il faut ensuite s'en remettre aux valeurs expérimentales (``*``) qui m'ont donné un **score de 58*3 arrondi à 200**
- Une fois qu'on a tout ça, il faut être sûr que les définitions seront toujours devant, on se retrouve avec un score pouvant d'après les tests aller jusqu'à environ 700, donc j'ai simplement décidé de **multiplier par 1000** pour m'assurer qu'une définition avec un très faible score passe quand-même devant.

(``*``) valeurs expérimentales :

- Il n'y a je crois théoriquement pas de "max" au score d'une requête "match" (celle de l'étape 2) mais lors de mes tests on est en gros entre 3 et 8 lorsqu'on est très précis, et la plupart du temps entre 1 et 2.
- Si on choisit une valeur X comme score de référence pour les champs "full text", on se retrouve avec **un score global du bloc n° 2 de 58*X**
- J'ai choisi une valeur de référence arbitraire de 3 pour qu'un titre matchant approximativement reste prioritaire sur un mot-clé, il s'agira pour vous d'ajuster ce curseur

**Comment by naholyr** [comment]
ping @jri-sp + @delphinelrcl pour la configuration

**Comment by jri-sp** [comment]
Pour moi pas de problème. C'est bien de la config qui va dans les fichiers .json du dossier config ?

**Comment by TomBor** [comment]
Merci @naholyr pour les explications !
Nous allons tester cela au fur et à mesure de l'ajout de ressources en préprod.

Par contre peux-t-on rendre le moteur plus humain : gestion des accents, des pluriels par exemple ?
https://www.elastic.co/guide/en/elasticsearch/guide/current/languages.html

**Comment by naholyr** [comment]
Il y a en effet pas mal de pistes intéressantes et pas forcément très
complexes dans ce guide, en revanche il faut faire une passe de
réindexation (gare aux backups ;)) car on doit alors stocker la version
"spécial recherche" du texte pour comparaison avec la recherche utilisateur
transformé :

   - Remove diacritics → très facile à mettre en place
   - Remove the distinction between singular and plural → plus complexe, il
   faudrait voir ce qui existe pour faire du stemming en français en Node,
   j'ai trouvé un module (https://www.npmjs.com/package/French-stemmer) qui
   a fort peu de références, ainsi qu'un autre nommé "jslingua" (testable
   ici : https://kariminf.github.io/jslingua.web/morpho.html les résultats
   m'ont peu convaincu)
   - Remove commonly used words or *stopwords* → plutôt simple avec une
   liste prédéfinie en général on a des résultats suffisants
   - Including synonyms → c'est le même principe que les stopwords, mais
   avec la problématique de stemming en plus
   - Check for misspellings or alternate spellings → assez complexe si on
   veut un résultat façon google, par contre si on veut être tolérant aux
   fautes un réglage du fuzzy devrait être suffisant, on peut imaginer mettre
   une valeur en configuration que vous pourriez ajuster en fonction des tests

Si on veut aller par là je pense qu'implémenter les filtres faciles
(diacritiques + mots-stop) et le réglage du fuzzy en configuration
donnerait déjà quelques résultats pour un investissement faible.

**Comment by TomBor** [comment]
Ta proposition de compromis me parait très bien. Ça sera déjà un saut qualitatif pour l'utilisateur.

**Comment by naholyr** [comment]
Le stockage d'une version "nettoyée" des principaux champs de recherche full-text (title, subtitle, description_fr, description_en) est implémentée.
Pour mettre à jour les documents existant, deux méthodes :

* Éditer chaque article/focus/image/carte/son/vidéo et re-cliquer sur "sauver"
* Le faire programmatiquement en lot en lançant la commande `yarn model-repl` puis en y exécutant ce code (enfin, Ctrl+C pour quitter une fois l'opération finie) :

```js
Resources.list().then(rs => Promise.all(rs.map(r => Resources.update(r.id, {}))))
```

**Comment by naholyr** [comment]
J'ai du remanier la feature pour le support des champs "nested", sinon on n'incluait pas les metas et paragraphes des articles.

A priori c'est tout bon maintenant. Ne reste qu'à rendre configurable le niveau de "fuzziness" si ce n'est pas trop long.

Note 1 : la bonne commande dans `yarn model-repl` pour forcer la mise à jour de toutes les ressources est la suivante (pas une mise à jour vide mais un update avec l'objet lui-même, sinon on ne déclenchait pas le calcul pour les définitions par exemple) :

```js
Resources.list().then(rs => Promise.all(rs.map(r => Resources.update(r.id, r))))
```

Note 2 : Je souhaitais initialement inclure un simple champ "fullTextSearch" au niveau de chaque ressource qui aurait été la concaténation de tous les champs dans lesquels on souhaite chercher, en version "nettoyée". Mais comme on applique un boost par champ, et que ces boost ainsi que les champs inclus dans la recherche sont configurables, cette idée n'a pu aboutir, c'est pourquoi chaque champ est individuellement dupliqué.

**Comment by naholyr** [comment]
Ajout du paramètre "fuzziness", placé sur "AUTO" par défaut (voir https://www.elastic.co/guide/en/elasticsearch/guide/current/fuzziness.html)

**Comment by TomBor** [comment]
Merci, l'usage du moteur est maintenant grandement amélioré !
