### ISSUE TITLE
Servir l'admin dans un /sousdossier

### ISSUE THREAD

**Issue by jri-sp** [AtelierCartographie/eatlas#81]
J'ai un nouveau souci depuis que je sers l'admin dans http://hostname/admin/

Les routes du client ne prennent pas en compte ce chemin de base et donc dès que l'appli React est chargée le `/admin/` disparait de l'URL et n'est pas intégré aux boutons/liens.
On ne peut pas non plus faire un refresh des pages parce que l'URL n'est pas la bonne.
Bref, tout est prévu pour fonctionner sur `/`.

Est-ce qu'on pourrait faire en sorte que la variable `PUBLIC_URL` soit également utilisée pour construire les routes et les liens ?

J'ai vu qu'on pouvait rajouter une option `basename` au routeur: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/BrowserRouter.md
mais j'y connais pas grand chose en React donc j'en appelle à votre expertise :)

Je pensais à un:
```
      <BrowserRouter basename={process.env.PUBLIC_URL}>
```
ici: https://github.com/AtelierCartographie/eatlas/blob/master/client/src/components/Root.js#L25

Merci!

**Comment by naholyr** [comment]
Je regarde ça demain, il y a de grandes chances que la piste du basename soit bonne. En revanche à ma connaissance elle ne prend pas une URL mais plutôt un "path", du coup il nous faudra une nouvelle variable dédiée à ça. Mais de là ça devrait faire le job.

**Comment by naholyr** [comment]
J'ai tenté un correctif basé là-dessus qui a l'air de fonctionner, en ajoutant la variable d'environnement `REACT_APP_ADMIN_BASENAME`.

J'aurais pu éviter de créer une nouvelle variable en parsant `REACT_APP_ADMIN_URL` mais je me méfie d'un éventuel cas où ça ne marcherait pas (même si je n'en ai pas trouvé…).

**Comment by naholyr** [comment]
Ne trouvant aucun cas où ça pourrait être différent, j'ai finalement supprimé la variable dédiée et je me base sur ADMIN_URL pour générer le *basename*. J'ai tout de même laissé son utilisation possible, ainsi si jamais on s'aperçoit que finalement il existe des cas tordus, il suffira de définir `REACT_APP_ADMIN_BASENAME` pour forcer la valeur.
