### ISSUE TITLE
Image de fond du topic

### ISSUE THREAD

**Issue by naholyr** [AtelierCartographie/eatlas#83]
Dans un premier temps, l'image est hardcodée en fonction du n° de topic

À terme ça devrait être éditable

**Comment by Delapouite** [comment]
Cette tache sera traitée rapidement dès que les 6/7 images de fond seront dispos directement via la feuille de style. Pas besoin de gérer l'upload pour un element decoratif.

**Comment by TomBor** [comment]
Pour le moment peux-t-on utiliser utiliser des copies du même fichier de fond ?
Comme ça nous le remplacerons plus tard

**Comment by Delapouite** [comment]
Dans le commit ci-dessus j'ai repris 9 fois l'embleme SciencesPo utilisé sur la page `A propos`.
Autrement dit, il faudra à terme remplacer les `/img/headers/topic-{1..9}.png` et probablement ajuster leur positionnement.
