### ISSUE TITLE
topics - le champ media url ne doit pas etre obligatoire

### ISSUE THREAD

**Issue by Delapouite** [AtelierCartographie/eatlas#85]

**Comment by delphinelrcl** [comment]
Il faut également ajouter 2 champs (non obligatoires) lors de la création d'une rubrique :  
- "image"  'sélectionner ou importer une image)
- "description"

**Comment by Delapouite** [comment]
Actuellement les topics (parties) affichent une video sur le site public ; cela correspond au champ `mediaUrl` dans lequel est renseignée une URL vimeo.

- Le champ **description** va t'il etre utilisé sur le site public ou est-ce seulement pour apporter des précisions aux utilisateurs du back-office ?
- De même quel sera le traitement du champ **image**? S'agit il de l'image de fond (grisée) d'une partie sur le site public tel que reférée ici : https://github.com/AtelierCartographie/eatlas/issues/83 ? Ou d'une image qui va apparaitre à la place des videos sur la maquette actuelle ?

**Comment by delphinelrcl** [comment]
Le champ image sera utilisé si nous n'avons pas le temps de produire les vidéos à temps pour la sortie de l'atlas. Il devra donc s'afficher  sur le site public. Ce champ est différent de #83 
Idem pour le champ description, qui devra aussi s'afficher en public.
