### ISSUE TITLE
resource - jongler entre source / copyright / credit

### ISSUE THREAD

**Issue by Delapouite** [AtelierCartographie/eatlas#88]

**Comment by TomBor** [comment]
+   Image, son et vidéo = `copyright`
+   Carte = `source`

**Comment by TomBor** [comment]
À ce jour, pour les ressources image et carte, il y a les deux champs `copyright`et `source`.
Mais l e champs `source` n'est pas visible dans le front office.

À l'usage, le seul champs `copyright`nous suffit, quand c'est une image nous le remplissons avec un vrai copyright, quand c'est une carte nous le remplissons avec une source car le copyright est en dur dans le jpg de la carte.

On peut donc supprimer le champs source.

Désolé pour le malentendu.

**Comment by TomBor** [comment]
Finalement le champs source est bien gardé et utilisé pour les cartes.
Ce qui permet de bien mettre une source dans le champs source pour les cartes et un copyright dans le champs copyright pour les photos. Et il n'y a plus d'usage différent d'une même méta.
