### ISSUE TITLE
BO - l'import du lexique ne fonctionne pas

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#97]
Le message d'erreur suivant s'affiche :  
Erreur:child "definitions" fails because ["definitions" at position 9 fails because [child "dt" fails because ["dt" is not allowed to be empty]]]

Erreur:child "definitions" fails because ["definitions" at position 8 fails because [child "dd" fails because ["dd" is not allowed to be empty]]]

**Comment by delphinelrcl** [comment]
[lexique.docx](https://github.com/AtelierCartographie/eatlas/files/1879991/lexique.docx)

**Comment by Delapouite** [comment]
Merci.

Le format du document a pas mal changé depuis celui que j'avais à l'origine, d'où cette incapacité à le parser.

On passe de 10 defs à 169 defs ce qui est beaucoup plus representatif du lexique final et tous les formatages chelou que l'on peut y croiser (`<h2>` fantomes, definitions manquantes, nombre de signes…).

Le nouveau parseur est plus selectif et donc plus robuste. On devrait avoir beaucoup moins de "faux positifs".
