### ISSUE TITLE
BO : rendre le champ description facultatif

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#98]
pour tous les types

**Comment by delphinelrcl** [comment]
le champ description est toujours obligatoire pour les articles et focus...

**Comment by Delapouite** [comment]
Je ne comprends pas dans quel sens lire la dernière remarque.

Pour le moment voici ce que j'ai:

![image](https://user-images.githubusercontent.com/39315/39513679-670626da-4df5-11e8-994d-507f27a31f73.png)

Autrement dit le champ description est facultatif sur les articles (et focus).

La demande est elle:

1 - (re)rendre obligatoire le champ description pour les articles
ou
2 - il y a un bug, et le champs apparait toujours comme obligatoire pour les articles chez vous

**Comment by antoinerio** [comment]
Bonjour Bruno,
Réponse 2 !
Le champs description est obligatoire pour les articles et focus alors qu'il devrait être facultatif.
<img width="1704" alt="bug-description-focus" src="https://user-images.githubusercontent.com/16940767/39514434-676f776e-4df7-11e8-8465-dd46d855ddbe.png">
